Iterable/iterable-swift-sdk

- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- README.md
- sample-apps/objc-sample-app/Podfile
- sample-apps/objc-sample-app/objc-sample-app.xcodeproj/project.pbxproj
- sample-apps/swift-sample-app/Podfile
- sample-apps/swift-sample-app/swift-sample-app.xcodeproj/project.pbxproj
1. Create new podspec.
2. Add README.md (more details to be added via another PR).
3. Fix sample apps.
> [ITBL-5457]-public-cocoapods

- swift-sdk/IterableAPIImplementation.swift
Dispatch async fix applied to Swift SDK.
> [ITBL-5618]-async-fix-for-swift

- Tests/swift-sdk-swift-tests/IterableAPITests.swift
- swift-sdk/IterableAPIInternal.swift
Set class for NSKeyedUnarchiver so that Objective C attribution info.
> [ITBL-5860] - set class for deserialization

- Tests/swift-sdk-objc-tests/IterableAPIResponseTests.m
- Tests/swift-sdk-swift-tests/IterableAPITests.swift
- Tests/swift-sdk-swift-tests/IterableRequestUtilTests.swift
- Tests/swift-sdk-swift-tests/Mocks.swift
- Tests/swift-sdk-swift-tests/TestUtils.swift
- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/IterableAPI.swift
- swift-sdk/IterableAPIInternal+Extension.swift
- swift-sdk/IterableAPIInternal.swift
- swift-sdk/IterableAPNSUtil.swift
- swift-sdk/IterableRequestUtil.swift
- swift-sdk/NetworkHelper.swift
More unit tests and refactoring.
> [ITBL-5914] - codecov part 2

- Tests/swift-sdk-swift-tests/DeferredDeeplinkTests.swift
- Tests/swift-sdk-swift-tests/IterableAPIResponseTests.swift
- Tests/swift-sdk-swift-tests/IterableAPITests.swift
- Tests/swift-sdk-swift-tests/IterableAutoRegistrationTests.swift
- Tests/swift-sdk-swift-tests/IterableNotificationResponseTests.swift
- Tests/swift-sdk-swift-tests/TestUtils.swift
- notification-extension/ITBNotificationServiceExtension.swift
- swift-sdk/ITBConsts.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/IterableAppIntegrationInternal.swift
- swift-sdk/Internal/IterableDeeplinkManager.swift
- swift-sdk/Internal/IterableInAppManager.swift
- swift-sdk/Internal/IterableRequestUtil.swift
- swift-sdk/Internal/UserDefaultsLocalStorage.swift
- swift-sdk/IterableAPI.swift
- swift-sdk/IterableConfig.swift
- swift-sdk/IterableConstants.h
- swift-sdk/IterableConstants.m
Move consts from Objc to Swift. Organize them better.
> [Itbl-5475] - refactor consts

- Tests/swift-sdk-swift-tests/PromiseTests.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/IterableInAppManager.swift
- swift-sdk/Internal/NetworkHelper.swift
- swift-sdk/Internal/Promise.swift
Renamed onFailure to onError for Future.
Refactor spawnInApp method.
> [MOB-1] - Use Future Internally

- Tests/swift-sdk-swift-tests/IterableRequestUtilTests.swift
- swift-sdk/Internal/IterableRequestUtil.swift
> [MOB-238] - Encoding get url query parameters

- Tests/swift-sdk-swift-tests/InAppTests.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/InAppPersistence.swift
1. Need to persist 'read'
2. Call inboxChanged event when deleting a message.
> [MOB-281] - Minor overlooked changes

- swift-sdk.xcodeproj/xcshareddata/xcschemes/ios9-tests.xcscheme
- swift-sdk.xcodeproj/xcshareddata/xcschemes/swift-sdk.xcscheme
This fixes https://github.com/Iterable/swift-sdk/issues/69
> Do not archive `host-app` target

- .travis.yml
- Tests/common/CommonMocks.swift
- Tests/swift-sdk-swift-tests/InAppParsingTests.swift
- Tests/swift-sdk-swift-tests/InAppTests.swift
- Tests/swift-sdk-swift-tests/InboxTests.swift
- Tests/swift-sdk-swift-tests/TestInAppPayloadGenerator.swift
- host-app/ViewController.swift
- swift-sdk/Internal/InAppDisplayer.swift
- swift-sdk/Internal/InAppHelper.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/IterableHtmlMessageViewController.swift
- swift-sdk/Internal/Promise.swift
- swift-sdk/IterableAPI.swift
- swift-sdk/IterableMessaging.swift
1. itbl:// for internal
2. action:// for other
> [MOB-290] - url schemes for in-app clicked url

- Tests/swift-sdk-swift-tests/IterableAPITests.swift
- swift-sdk/Internal/IterableAPIInternal.swift
Add preferUserId = true when using updateUser  using userId.
> [MOB-357] - Prefer user id

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/IterableInboxNavigationViewController.swift
- swift-sdk/IterableInboxViewController.swift
> [MOB-339] - Nav Controller

- Tests/common/CommonExtensions.swift
- Tests/common/CommonMocks.swift
- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/InAppInternal.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/IterableAPIInternal.swift
Better dependency injection for IterableAPIInternal
> [MOB-364] - Dependency Injection

- Tests/swift-sdk-swift-tests/InAppParsingTests.swift
- Tests/swift-sdk-swift-tests/InAppTests.swift
- Tests/swift-sdk-swift-tests/TestInAppPayloadGenerator.swift
- Tests/swift-sdk-swift-tests/TestUtils.swift
- host-app/ViewController.swift
- swift-sdk/ITBConsts.swift
- swift-sdk/Internal/ClassExtensions.swift
- swift-sdk/Internal/InAppMessageParser.swift
- swift-sdk/Internal/InAppPersistence.swift
- swift-sdk/Internal/InboxMessageViewModel.swift
- swift-sdk/Internal/IterableUtil.swift
- swift-sdk/IterableInboxCell.swift
- swift-sdk/IterableInboxViewController.swift
- swift-sdk/IterableMessaging.swift
- swift-sdk/Resources/IterableInboxCell.xib
1. add createdAt
2. rename subTitle => subtitle.
> [MOB-376] - backend compatibility

- Tests/swift-sdk-swift-tests/InAppTests.swift
- swift-sdk/Internal/InAppHelper.swift
use itbl:// for backward compatibility.
> [MOB-380] iterable namespace fix for master

- Tests/swift-sdk-swift-tests/InAppTests.swift
- swift-sdk/ITBConsts.swift
- swift-sdk/Internal/InAppHelper.swift
url scheme itbl:// for backward compatibility.
> [MOB-380] - url scheme iterable:// for iterable custom actions.

- BETA-TOS.md
- README.md
- Added Beta SDK ToS to README; added link to Iterable's iOS SDK release notes
> Added Beta SDK ToS to README; added link to Iterable's iOS SDK release notes

- README.md
- sample-apps/objc-sample-app/Podfile
- sample-apps/swift-sample-app/Podfile
Clarified instructions about `use_frameworks!` (for stable branch)
> Clarified instructions about `use_frameworks!` (for stable branch)

- README.md
Added information about requesting permission to receive push notifications.
> Push auth request

- host-app/ViewController.swift
- swift-sdk/Internal/InboxViewControllerViewModel.swift
2. Check for new messages on initialization.
> [MOB-474] - fix host app to now display view controller on main thread.

- README.md
The CocoaPods badge example can be seen here: https://badge.fury.io/for/co/Iterable-iOS-SDK
> Add updating pod badge and organize them

- Tests/swift-sdk-swift-tests/InAppHelperTests.swift
- Tests/swift-sdk-swift-tests/IterableAPITests.swift
- Tests/swift-sdk-swift-tests/IterableAutoRegistrationTests.swift
- swift-sdk/ITBConsts.swift
- swift-sdk/Internal/IterableAPIInternal.swift
Tests were also adjusted to reflect the use of the new key.
> Change header to use Api-Key instead of api_key for POSTs

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/ITBConsts.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/DateProvider.swift
- swift-sdk/Internal/EmptyInAppManager.swift
- swift-sdk/Internal/InAppContentParser.swift
- swift-sdk/Internal/InAppDisplayer.swift
- swift-sdk/Internal/InAppHelper.swift
- swift-sdk/Internal/InAppInternal.swift
- swift-sdk/Internal/InAppManager+Functions.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/IterableActionRunner.swift
- swift-sdk/Internal/UserDefaultsLocalStorage.swift
- swift-sdk/IterableAction.swift
- swift-sdk/IterableActionContext.swift
- swift-sdk/IterableConfig.swift
- swift-sdk/IterableInboxViewController.swift
- swift-sdk/IterableMessaging.swift
- swift-sdk/IterableNotificationMetadata.swift
Just spacing standardizing for a bunch of files; not comprehensive
> Code clean up

- swift-sdk/Internal/EmptyInAppManager.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/InboxViewControllerViewModel.swift
- swift-sdk/Internal/IterableHtmlMessageViewController.swift
- swift-sdk/IterableInboxViewController.swift
- swift-sdk/IterableMessaging.swift
Currently only inboxMode = .nav is supported.
> [MOB-607] - Refactored code to add `inboxMode`.

- Tests/ui-tests/InboxUITests.swift
- host-app/Base.lproj/Main.storyboard
- host-app/ViewController.swift
- swift-sdk/IterableInboxNavigationViewController.swift
Allow switching inbox behavior. We allow choosing between `nav` mode which shows inbox items in navigation controller. and `popup' which shows inbox message as popup.
> [MOB-609] - Switch between Popup and Nav

- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/EmptyInAppManager.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/IterableMessaging.swift
Need to add back method in public api.
> [MOB-659] - InAppManager.remove(:message) method issues

- Tests/common/CommonMocks.swift
- Tests/swift-sdk-swift-tests/InAppParsingTests.swift
- Tests/swift-sdk-swift-tests/InAppTests.swift
- Tests/swift-sdk-swift-tests/InboxTests.swift
- Tests/swift-sdk-swift-tests/IterableAPITests.swift
- Tests/swift-sdk-swift-tests/TestUtils.swift
- swift-sdk/ITBConsts.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ClassExtensions.swift
- swift-sdk/Internal/DeviceInfo.swift
- swift-sdk/Internal/InAppInternal.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/IterableAPI.swift
- swift-sdk/IterableConfig.swift
- swift-sdk/IterableMessaging.swift
Also defaults to 'inApp' where it makes sense.
> [MOB-748] - rename unknown to other

- Tests/swift-sdk-swift-tests/InAppParsingTests.swift
- Tests/swift-sdk-swift-tests/IterableAPIResponseTests.swift
- Tests/swift-sdk-swift-tests/IterableAPITests.swift
- Tests/swift-sdk-swift-tests/RequestCreatorTests.swift
- Tests/swift-sdk-swift-tests/TestUtils.swift
- swift-sdk/ITBConsts.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/InAppInternal.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/RequestCreator.swift
Moved it out of messageContext and into top level.
> [MOB-784] - move deviceinfo out

- swift-sdk/Resources/IterableInboxCell.xib
> [MOB-858] - Fix background color of image view. 

- .travis.yml
- Tests/swift-sdk-swift-tests/InAppTests.swift
- swift-sdk/Internal/InAppManager+Functions.swift
- swift-sdk/Internal/InAppManager.swift
Rewrote a couple of intermittently failing unit tests.
1. Replace with predicate
2. Use dateProvider.
> [MOB-863] - flaky tests

- swift-sdk/IterableInboxNavigationViewController.swift
- swift-sdk/IterableInboxViewController.swift
Dynamic instantiation of view delegate for inbox view controller.
> [MOB-930] - inbox customization 4

- .travis.yml
- Tests/common/CommonExtensions.swift
- Tests/common/CommonMocks.swift
- Tests/swift-sdk-swift-tests/InAppTests.swift
- Tests/swift-sdk-swift-tests/InboxTests.swift
- Tests/swift-sdk-swift-tests/PromiseTests.swift
- swift-sdk.xcodeproj/xcshareddata/xcschemes/swift-sdk.xcscheme
- swift-sdk/Internal/EmptyInAppManager.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/IterableLogging.swift
- swift-sdk/Internal/Promise.swift
- swift-sdk/IterableAPI.swift
> [MOB-967] - flaky tests

- swift-sdk/Internal/IterableLogging.swift
A fix for https://github.com/Iterable/swift-sdk/issues/214
> [MOB-973] Add inits for other logging delegates

- swift-sdk/IterableInboxNavigationViewController.swift
This allows us to set this from storyboard.
> [MOB-1106] - Allow setting large titles for iterable nav controller

- Tests/common/CommonMocks.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/IterableAppIntegrationInternal.swift
Removed unused methods properties etc.
> [MOB-1125] - lncrease IterableAPIInternal test coverage

- Tests/swift-sdk-swift-tests/InboxViewControllerViewModelTests.swift
- Tests/swift-sdk-swift-tests/SampleInboxViewDelegateImplementations.swift
- inbox-ui-tests-app/MainViewController.swift
- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/IterableInboxViewController.swift
Removed sample mappers from public SDK.
> [MOB-1220] - reorg mappers

- README.md
> Inbox README ToC and link fixes

- tests/swift-sdk-swift-tests/IterableNotificationResponseTests.swift
> [MOB-1538] - Test/mob 1538 notification response

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk.xcodeproj/xcshareddata/xcschemes/swift-sdk.xcscheme
- tests/endpoint-tests/EndpointTests.swift
- tests/endpoint-tests/Environment.swift
- tests/endpoint-tests/Info.plist
- tests/endpoint-tests/IterableAPISupport.swift
Tests for updateUser and updateEmail.
Read api key from environment.
> [MOB-1807] - endpoint tests

- tests/endpoint-tests/EndpointTests.swift
Add tests for trackPurchase, trackPushOpen and trackEvent.
> [MOB-1808] - More e2e tests

- swift-sdk/Internal/IterableAPICallTaskProcessor.swift
- swift-sdk/Internal/IterableTaskResult.swift
- swift-sdk/Internal/NetworkHelper.swift
- swift-sdk/Internal/Promise.swift
- tests/offline-events-tests/TaskProcessorTests.swift
… 2. Return status code and error from NetworkSession.
> [MOB-1979] - TaskProcessor handle success and failure for network unavailable.

- README.md
> Terms of Service => Disclaimer

- Package.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/IterableCoreDataPersistence.swift
- swift-sdk/Internal/IterableTaskRunner.swift
- swift-sdk/Internal/NetworkConnectivityManager.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestProcessor.swift
- swift-sdk/Internal/RequestProcessorProtocol.swift
- swift-sdk/IterableConfig.swift
- tests/offline-events-tests/RequestProcessorTests.swift
Add IterableTaskRunner to request processor.
> [MOB-2041] - Add task runner to request processor.

- swift-sdk/Internal/InAppDisplayer.swift
- swift-sdk/Internal/IterableHtmlMessageViewController.swift
- swift-sdk/IterableMessaging.swift
> [MOB-2223] - Require iOS version 14 for `systemBackgroundColor`

- swift-sdk/Internal/InAppCalculations.swift
- swift-sdk/Internal/InAppContentParser.swift
- swift-sdk/Internal/InAppDisplayer.swift
- swift-sdk/Internal/InAppPersistence.swift
- swift-sdk/Internal/IterableHtmlMessageViewController.swift
- swift-sdk/IterableMessaging.swift
- tests/swift-sdk-swift-tests/InAppFilePersistenceTests.swift
- tests/swift-sdk-swift-tests/InAppTests.swift
1. Make backgroundColor nullable for WebView. 2. Need to animate backgound color independently of `shouldAnimate`.
> [MOB-2239] - In app animation bug fix 

- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/IterableAppIntegrationInternal.swift
- swift-sdk/IterableAppIntegration.swift
- tests/common/CommonMocks.swift
Fix https://iterable.atlassian.net/browse/MOB-2343.
> [MOB-2343] - RN initialization

- swift-sdk/Constants.swift
- swift-sdk/Internal/IterableAPICallRequest.swift
- swift-sdk/Internal/IterableAPICallTaskProcessor.swift
- swift-sdk/Internal/IterableRequest.swift
- swift-sdk/Internal/IterableRequestUtil.swift
- swift-sdk/Internal/IterableTask.swift
- swift-sdk/Internal/IterableTaskRunner.swift
- tests/offline-events-tests/RequestProcessorTests.swift
- tests/offline-events-tests/TaskProcessorTests.swift
- tests/offline-events-tests/TaskRunnerTests.swift
- tests/swift-sdk-swift-tests/InAppTests.swift
Add createdAt to request body of POST messages.
Add sentAt to request header.
> [MOB-2400] - Add createdAt and sentAt

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/LegacyRequestHandler.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- swift-sdk/Internal/RequestProcessorProtocol.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/offline-events-tests/RequestProcessorTests.swift
See this doc for design decisions.
https://iterable.slab.com/posts/spike-what-to-do-with-pending-tasks-when-logging-a-user-out-vbp99ern
> [MOB-2445] - Certain calls are online only

- swift-sdk/Internal/AuthManager.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- tests/swift-sdk-swift-tests/AuthTests.swift
https://iterable.atlassian.net/browse/MOB-2365
https://iterable.atlassian.net/browse/MOB-2426
> [MOB-2365] account for more JWT cases

- .github/pull_request_template.md
* [MOB-XXXX](https://iterable.atlassian.net/browse/JIRA-XXXX)
> minor edit to PR template

- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/IterableAPICallRequest.swift
- swift-sdk/Internal/IterableAPICallTaskProcessor.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/IterableUtil.swift
- swift-sdk/Internal/LegacyRequestHandler.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- tests/common/CommonMocks.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/offline-events-tests/TaskProcessorTests.swift
- tests/offline-events-tests/TaskRunnerTests.swift
- tests/swift-sdk-swift-tests/IterableAPIResponseTests.swift
- tests/swift-sdk-swift-tests/RequestCreatorTests.swift
* [MOB-2478](https://iterable.atlassian.net/browse/MOB-2478)
> Added `createdAt` to all request body. Added `sentAt` to all request headers. 
Added tests.
> [MOB-2478] - Add createdAt, sentAt to all requests. Add tests.

- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/LegacyRequestHandler.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- tests/common/CommonExtensions.swift
- tests/endpoint-tests/E2EDependencyContainer.swift
- tests/endpoint-tests/OfflineModeE2ETests.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/offline-events-tests/TaskRunnerTests.swift
* [MOB-2543](https://iterable.atlassian.net/browse/MOB-2543)
> [MOB-2543] - Fix offline mode issues

- swift-sdk/Constants.swift
- swift-sdk/Internal/IterableAPICallRequest.swift
- swift-sdk/Internal/IterableAPICallTaskProcessor.swift
- tests/swift-sdk-swift-tests/RequestCreatorTests.swift
- tests/swift-sdk-swift-tests/TestUtils.swift
* [MOB-2547](https://iterable.atlassian.net/browse/MOB-2547)
> Add header 'SDK-Request-Processor' = 'Online' | 'Offline' to header.
> [MOB-2547] - Add "SDK-Request-Processor" field to header.

- swift-sdk/Constants.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/offline-events-tests/TaskProcessorTests.swift
- tests/offline-events-tests/TaskRunnerTests.swift
* [MOB-2544](https://iterable.atlassian.net/browse/MOB-2544)
> Change sent from SDK from 'sentAt' to 'Sent-At'
> [MOB-2544] - Change header from 'sentAt' to 'Sent-At'

- swift-sdk/IterableAPI.swift
* [MOB-2492](https://iterable.atlassian.net/browse/MOB-2492)
> Provide a callback when calling IterableAPI.initialize2 from React Native.
> [MOB-2492] - Need callback for reporting initialization is done.

- swift-sdk/Internal/ResourceHelper.swift
* [MOB-2565](https://iterable.atlassian.net/browse/MOB-2565)
> Change folder name fore Cocoapods resources.
> [MOB-2565] - Change resource folder name for Cocoapods.

- swift-sdk/Internal/InboxViewControllerViewModel.swift
- swift-sdk/IterableInboxNavigationViewController.swift
- swift-sdk/IterableInboxViewController.swift
* [MOB-2157](https://iterable.atlassian.net/browse/MOB-2157)
> Issue detail is in jira ticket. We want to give the users an option to add "there are no messages in your inbox" message.
> [MOB-2157] - No messages view

- swift-sdk/Internal/Promise.swift
- swift-sdk/IterableInboxNavigationViewController.swift
- swift-sdk/IterableInboxViewController.swift
* [MOB-2645](https://iterable.atlassian.net/browse/MOB-2645)
> Reduce some logging.
> [MOB-2645] - Reduce logging.

- swift-sdk/Internal/CoreDataUtil.swift
- swift-sdk/Internal/IterableCoreDataPersistence.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/IterableInboxViewController.swift
* [MOB-2206](https://iterable.atlassian.net/browse/MOB-2206)
> Removed fatalError from places where we could return default or an error.
> [MOB-2206] - Remove fatalerror

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/InAppHelper.swift
- swift-sdk/Internal/InAppManager+Functions.swift
- tests/swift-sdk-swift-tests/in-app-tests/InAppMessageProcessorTests.swift
- tests/swift-sdk-swift-tests/in-app-tests/InAppPersistenceTests.swift
- tests/swift-sdk-swift-tests/in-app-tests/InAppTests.swift
* [MOB-2605](https://iterable.atlassian.net/browse/MOB-2605)
* skips over showing in-app messages that have already been read
> [MOB-2605] persistent read state

- tests/swift-sdk-swift-tests/in-app-tests/InAppPriorityTests.swift
* [MOB-2568](https://iterable.atlassian.net/browse/MOB-2568)
* add another test for in-app priority
> [MOB-2568] add in-app priority test for sorting on a list

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-2787](https://iterable.atlassian.net/browse/MOB-2787)
* prepares the `master` branch for the new beta release
> [MOB-2787] version 6.3.0-beta3

- tests/endpoint-tests/EndpointTests.swift
* [MOB-2683](https://iterable.atlassian.net/browse/MOB-2683)
> Update email and update user calls are failing intermittently in integration tests environment. Remove those so that we can rely more on your integration tests.
> [MOB-2683] - Remove flaky tests

- swift-sdk/Internal/InboxViewControllerViewModel.swift
- swift-sdk/IterableInboxViewController.swift
- tests/swift-sdk-swift-tests/inbox-tests/InboxViewControllerViewModelTests.swift
* [MOB-2757](https://iterable.atlassian.net/browse/MOB-2757)
> The animation glitches are due to some issues with our Diff library. We weren't getting back any information about updates. Fixed it so that we get information about updates and not just inserts and deletes.
> [MOB-2757] - Fix animation glitch

- tests/offline-events-tests/RequestHandlerTests.swift
…end feature flag.
* [MOB-2532](https://iterable.atlassian.net/browse/MOB-2532)
> Add tests to check for turning on off offline processor based on backend feature flag.
> [MOB-2532] - Feature flags tests for offline processor

- tests/offline-events-tests/RequestHandlerTests.swift
* [MOB-2533](https://iterable.atlassian.net/browse/MOB-2533)
> Test that offline mode is being read from local storage properly.
> [MOB-2533]- Test that offline mode is being read from local storage properly.

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/CoreDataUtil.swift
- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/HealthMonitor.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/IterableAPICallRequest.swift
- swift-sdk/Internal/IterableAPICallTaskProcessor.swift
- swift-sdk/Internal/IterableCoreDataPersistence.swift
- swift-sdk/Internal/IterablePersistence.swift
- swift-sdk/Internal/IterableTaskRunner.swift
- swift-sdk/Internal/IterableTaskScheduler.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- tests/common/CommonExtensions.swift
- tests/common/CommonMocks.swift
- tests/offline-events-tests/HealthMonitorTests.swift
- tests/offline-events-tests/MockPersistence.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/offline-events-tests/TaskRunnerTests.swift
- tests/offline-events-tests/TaskSchedulerTests.swift
- tests/offline-events-tests/TasksCRUDTests.swift
- tests/unit-tests/RequestCreatorTests.swift
* [MOB-2850](https://iterable.atlassian.net/browse/MOB-2850)
> 
Health monitor should catch all database errors and switch processor to online if an error is found.
It should, if possible, try to recover a failed scheduled task.
> [MOB-2850] - Offline events health monitor

- CHANGELOG.md
* N/A
* merges the changes we had from `stable` into `master`, which is only the changelog
> squash changes from stable to merge into master

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-2883](https://iterable.atlassian.net/browse/MOB-2883)
* new beta SDK for offline events
> [MOB-2883] version 6.3.0-beta4

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/Internal/Models.swift
- swift-sdk/IterableAPI.swift
* [MOB-2967](https://iterable.atlassian.net/browse/MOB-2967)
* changes to prepare the SDK for the release of 6.3.0
> [MOB-2967] version 6.3.0

- swift-sdk/CommerceItem.swift
- swift-sdk/Constants.swift
- swift-sdk/Internal/RequestCreator.swift
- tests/unit-tests/CommerceItemTests.swift
* [MOB-2921](https://iterable.atlassian.net/browse/MOB-2921)
* extends the functionality of `trackPurchase` to match the current API
> [MOB-2921] update commerceitem to allow optional fields

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-2992](https://iterable.atlassian.net/browse/MOB-2992)
* SDK version 6.3.1 release
> [MOB-2992] version 6.3.1

- CHANGELOG.md
> Updated CHANGELOG for iOS 6.3.1

- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/IterableTaskRunner.swift
- swift-sdk/Internal/WebViewProtocol.swift
* [MOB-3034](https://iterable.atlassian.net/browse/MOB-3034)
* slight maintenance (no functional changes) while browsing code
> [MOB-3034] sdk maintenance

- swift-sdk/Constants.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/LegacyRequestHandler.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- swift-sdk/Internal/RequestProcessorProtocol.swift
- swift-sdk/IterableAPI.swift
* [MOB-725](https://iterable.atlassian.net/browse/MOB-725)
* Adds the [updateCart API](https://api.iterable.com/api/docs#commerce_updateCart) into our SDK
* This PR adds the call into our SDK, while the part 2 PR fixes and adds the test case for it. It's also split out because part 2 has a lot of refactoring with our test files that I didn't want to show up here. For our PR tests, we'll want to use the part 2 PR for that, as this one does have an error with them (and it was cleaner to split it out like this). The part 2 PR is branched off of this completed part 1 PR.
> [MOB-725] updateCart (part 1)

- swift-sdk/Internal/RequestCreator.swift
- tests/unit-tests/InAppHelperTests.swift
- tests/unit-tests/IterableAPITests.swift
* [MOB-725](https://iterable.atlassian.net/browse/MOB-725)
* Adds the [updateCart API](https://api.iterable.com/api/docs#commerce_updateCart) into our SDK
* The part 2 of the other PR which fixes and adds test case related to the part 1 PR. It also has a bunch of quick refactoring that was convenient while I was working on these files.
> [MOB-725] updateCart (part 2)

- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/LegacyRequestHandler.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- swift-sdk/Internal/RequestProcessorProtocol.swift
- swift-sdk/IterableAPI.swift
- tests/unit-tests/InAppHelperTests.swift
* [MOB-725](https://iterable.atlassian.net/browse/MOB-725)
* removes the top level `dataFields` in `updateCart` (it isn't actually a part of the API)
* also had some fixes I missed in other PRs
> [MOB-725] remove top level dataFields

- swift-sdk/CommerceItem.swift
- swift-sdk/Constants.swift
- tests/unit-tests/CommerceItemTests.swift
* [MOB-3180](https://iterable.atlassian.net/browse/MOB-3180)
* adds `dataFields` to `CommerceItem` to match the API
> [MOB-3180] update cart items datafields

- notification-extension/NotificationContentParser.swift
* [MOB-3265](https://iterable.atlassian.net/browse/MOB-3265)
* adds needed import to NSE content parser for when importing the SDK externally
> [MOB-3265] add import to NSE content parser

- tests/ui-tests/UITests.swift
* [MOB-2110](https://iterable.atlassian.net/browse/MOB-2110)
> Needed to change the push notifications are handled by UI tests.
> [MOB-2110] - New method for UI testing push notifications.

- swift-sdk/IterableInboxViewController.swift
* [MOB-3470](https://iterable.atlassian.net/browse/MOB-3470)
Fix alignment of no messages title. Make it centered.
> [MOB-3470] - Fix alignment of "no messages title".

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Constants.swift
- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/IterableKeychain.swift
- swift-sdk/Internal/IterableUserDefaults.swift
- swift-sdk/Internal/LocalStorage.swift
- swift-sdk/Internal/LocalStorageProtocol.swift
- swift-sdk/Internal/UserDefaultsLocalStorage.swift
- tests/endpoint-tests/E2EDependencyContainer.swift
- tests/unit-tests/IterableAPITests.swift
- tests/unit-tests/KeychainWrapperTests.swift
- tests/unit-tests/LocalStorageTests.swift
* [MOB-3596](https://iterable.atlassian.net/browse/MOB-XXXX)
> We need to store JWT auth token in keychain instead of UserDefaults. More details are here
https://iterable.slab.com/posts/cleartext-jwt-storage-remediation-wnj6gj9y.
> [MOB-3596] - Keychain to store JWT token

- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/IterableAppIntegrationInternal.swift
- swift-sdk/Internal/LegacyRequestHandler.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/unit-tests/Mocks.swift
* [MOB-3701](https://iterable.atlassian.net/browse/MOB-3701)
> [MOB-3701] - Fix crash

- swift-sdk/Internal/IterableHtmlMessageViewController.swift
* [MOB-3597](https://iterable.atlassian.net/browse/MOB-3597)
> Disable execution of content Javascript for iOS >= 14
> [MOB-3597] - Disable execution of content Javascript for WebViews

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/InAppHelper.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/IterableActionRunner.swift
- swift-sdk/Internal/IterableAppIntegrationInternal.swift
- swift-sdk/Internal/IterableDeepLinkManager.swift
- swift-sdk/IterableConfig.swift
- tests/hosting-apps/ui-tests-app/ViewController.swift
- tests/ui-tests/UITests.swift
- tests/unit-tests/DeepLinkTests.swift
- tests/unit-tests/InAppNavigationTests.swift
- tests/unit-tests/IterableActionRunnerTests.swift
- tests/unit-tests/TestInAppPayloadGenerator.swift
* [MOB-3691](https://iterable.atlassian.net/browse/MOB-3691)
> 
Block all protocols except `https`. Add IterableConfig value to override this behavior.
> [MOB-3691] - WebView navigation allowed protocols

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/InAppCalculations.swift
- swift-sdk/Internal/IterableInboxCell+Layout.swift
- swift-sdk/Internal/UIColor+Extension.swift
- swift-sdk/IterableInboxViewController.swift
* [MOB-3584](https://iterable.atlassian.net/browse/MOB-3584)
> Use system colors instead of hard coded colors.
> [MOB-3584] - Use system colors for iOS 13 onwards.

- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/IterableActionRunner.swift
- tests/unit-tests/DeepLinkTests.swift
- tests/unit-tests/IterableActionRunnerTests.swift
* [MOB-3725](https://iterable.atlassian.net/browse/MOB-3725)
> Allow opening urls from universal links also.
> [MOB-3725] - Allow opening of url from universal links also.

- swift-sdk/Internal/IterableDeepLinkManager.swift
- tests/unit-tests/DeepLinkTests.swift
…s Iterable deep link.
* [MOB-3724](https://iterable.atlassian.net/browse/MOB-3724)
> Return true/false for handleUniversalLink based on whether the link is Iterable deep link.
> [MOB-3724] - handleUniversalLink return value 

- swift-sdk/Internal/EmptyInAppManager.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/InboxState.swift
- swift-sdk/Internal/InboxViewControllerViewModel.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- swift-sdk/Internal/RequestProcessorProtocol.swift
- tests/common/CommonMocks.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/unit-tests/InboxViewControllerViewModelTests.swift
* [MOB-3867](https://iterable.atlassian.net/browse/MOB-XXXX)
> Add inbox session id to in app consume calls.
> [MOB-3867] - Add inbox session id to in app consume requests

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/IterableHtmlMessageViewController.swift
- tests/common/CommonMocks.swift
- tests/unit-tests/IterableHtmlMessageViewControllerTests.swift
* [MOB-3968](https://iterable.atlassian.net/browse/MOB-3968)
> Added encapsulation, mocks and unit tests.
> [MOB-3968 ] - Refactor IterableHtmlMessageViewController

- swift-sdk/Internal/InboxSessionManager.swift
- swift-sdk/Internal/InboxViewControllerViewModel.swift
- swift-sdk/Internal/InboxViewControllerViewModelProtocol.swift
- swift-sdk/Internal/IterableHtmlMessageViewController.swift
- swift-sdk/IterableInboxViewController.swift
- tests/unit-tests/InboxViewControllerViewModelTests.swift
* [MOB-4061](https://iterable.atlassian.net/browse/MOB-4061)
> Detailed discussion is present here
https://iterable.slab.com/posts/i-os-inbox-session-tracking-eu5q2lic
> [MOB-4061] - Bug: Fix iOS SDK session tracking

- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- swift-sdk/Internal/RequestProcessorProtocol.swift
- swift-sdk/IterableAPI.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/unit-tests/InAppHelperTests.swift
- tests/unit-tests/IterableAPITests.swift
* [MOB-4021](https://iterable.atlassian.net/browse/MOB-4021)
> Add optional campaignId and templateId to trackPurchase request
> [MOB-4021] - add optional campaignId and templateId to trackPurchase request

- swift-sdk.xcodeproj/project.pbxproj
- tests/inbox-ui-tests/InboxUITestsHelper.swift
- tests/inbox-ui-tests/NavInboxSessionUITests.swift
- tests/inbox-ui-tests/PopupInboxSessionUITests.swift
* [MOB-4101](https://iterable.atlassian.net/browse/MOB-4101)
> Added UI tests for mobile inbox session tracking.
> [MOB-4101] - Add UI tests for session tracking.

- .github/workflows/e2e.yml
- swift-sdk.xcodeproj/project.pbxproj
- tests/endpoint-tests/scripts/run_test.sh
* [MOB-4268](https://iterable.atlassian.net/browse/MOB-4268)
Upgrade to Xcode 13.
Embed host app.
> [MOB-4268] - Fix integration tests

- swift-sdk/swiftui/InboxViewRepresentable.swift
- swift-sdk/swiftui/IterableInboxView.swift
* [MOB-4215](https://iterable.atlassian.net/browse/MOB-4215)
> Remove unsupported architecture.
> [MOB-4215] - Fix SwiftUI

- swift-sdk/Internal/IterableCoreDataPersistence.swift
- tests/endpoint-tests/OfflineModeE2ETests.swift
- tests/offline-events-tests/HealthMonitorTests.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/offline-events-tests/TaskProcessorTests.swift
- tests/offline-events-tests/TaskRunnerTests.swift
- tests/offline-events-tests/TaskSchedulerTests.swift
- tests/offline-events-tests/TasksCRUDTests.swift
* [MOB-4274](https://iterable.atlassian.net/browse/MOB-4274)
> Mac catalyst XCFramework projects look in a different location for db file. We need to search in different locations for the file.
> [MOB-4274] - Check in multiple bundles for db bundle.

- swift-sdk.xcodeproj/project.pbxproj
* [MOB-4279](https://iterable.atlassian.net/browse/MOB-4279)
> Fix build order in Xcode
> [MOB-4279] - Xcode build order

- inbox-ui-tests-app.entitlements
- swift-sdk.xcodeproj/project.pbxproj
- tests/hosting-apps/ui-tests-app/ui-tests-app.entitlements
* [MOB-4275](https://iterable.atlassian.net/browse/MOB-4275)
> Add support for Mac Catalyst
> [MOB-4275] - Mac Catalyst support

- swift-sdk/Internal/AuthManager.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/NetworkHelper.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestProcessorUtil.swift
- tests/unit-tests/AuthTests.swift
* [MOB-4127](https://iterable.atlassian.net/browse/MOB-4127)
> 
We need to retry the request after obtaining JWT token if the original Jwt token is invalid.
> [MOB-4127] - Retry Jwt failure Requests for Online processor

- swift-sdk.xcodeproj/xcshareddata/xcschemes/swift-sdk.xcscheme
- swift-sdk/Internal/CoreDataUtil.swift
- swift-sdk/Internal/HealthMonitor.swift
- swift-sdk/Internal/IterableCoreDataPersistence.swift
- swift-sdk/Internal/IterablePersistence.swift
- swift-sdk/Internal/IterableTaskRunner.swift
- swift-sdk/Internal/IterableTaskScheduler.swift
- swift-sdk/Internal/Pending.swift
- swift-sdk/Internal/RequestHandler.swift
- tests/common/CommonMocks.swift
- tests/offline-events-tests/HealthMonitorTests.swift
- tests/offline-events-tests/MockPersistence.swift
- tests/offline-events-tests/TasksCRUDTests.swift
- tests/unit-tests/TestUtils.swift
* [MOB-4408](https://iterable.atlassian.net/browse/MOB-4408)
> 
All core data calls should be encapsulated inside `perform` or `performAndWait` blocks. Otherwise, if we turn on multi threaded debugging, exceptions are thrown.
> Fix core data multi threading debug errors

- swift-sdk/Constants.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/IterableUserDefaults.swift
- swift-sdk/Internal/LocalStorage.swift
- swift-sdk/Internal/LocalStorageProtocol.swift
- swift-sdk/Internal/Models.swift
- tests/common/CommonMocks.swift
- tests/endpoint-tests/OfflineModeE2ETests.swift
- tests/offline-events-tests/HealthMonitorTests.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/unit-tests/LocalStorageTests.swift
* [MOB-4593](https://iterable.atlassian.net/browse/MOB-XXXX)
> Use actual feature flag instead of beta feature flag.
> [MOB-4593] - Check for offlineMode flag instead of beta flag. Update unit tests.

- swift-sdk/Constants.swift
- swift-sdk/Internal/IterableKeychain.swift
- swift-sdk/Internal/LocalStorage.swift
- tests/unit-tests/LocalStorageTests.swift
* [MOB-4436](https://iterable.atlassian.net/browse/MOB-4436)
* adds `email` and `userId` into our keychain
> [MOB-4436] encrypt auth data

- swift-sdk/IterableInboxNavigationViewController.swift
- swift-sdk/IterableInboxViewController.swift
* [MOB-4616](https://iterable.atlassian.net/browse/MOB-4616)
* adds `@objcMembers` to `IterableInboxViewController` and `IterableInboxNavigationViewController` so they can be accessed in Objective-C
> [MOB-4616] tag inbox classes as objective-c available

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-4630](https://iterable.atlassian.net/browse/MOB-4630)
* release version 6.4.6
> [MOB-4630] update to version 6.4.6

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-4690](https://iterable.atlassian.net/browse/MOB-4690)
* preparing for release of version 6.4.7
> [MOB-4690] version 6.4.7

- swift-sdk/Internal/IterableUserDefaults.swift
- swift-sdk/Internal/LocalStorage.swift
* [MOB-4781](https://iterable.atlassian.net/browse/MOB-4781)
* creates a new migration function in `LocalStorage` for `lastPushPayload`
* cleans up/fixes the logic of the auth data migration a little bit for unexpected edge cases
> [MOB-4781] userdefaults migration refactor

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-4205](https://iterable.atlassian.net/browse/MOB-4205)
* prepares version 6.4.8 for release
> [MOB-4205] version  6.4.8

- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/InAppPersistence.swift
- swift-sdk/IterableConfig.swift
* [MOB-5115](https://iterable.atlassian.net/browse/MOB-5115)
> [MOB-5115] add iOS config for in memory in-app use

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-5134](https://iterable.atlassian.net/browse/MOB-5134)
> [MOB-5134] version 6.4.9

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-5345](https://iterable.atlassian.net/browse/MOB-5345)
Release 6.4.10
[MOB-5345]: https://iterable.atlassian.net/browse/MOB-5345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5345] - Release 6.4.10

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/IterableFlexMessage.swift
* [MOB-5386](https://iterable.atlassian.net/browse/MOB-5386)
[MOB-5386]: https://iterable.atlassian.net/browse/MOB-5386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5386] create flex message data type

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/EmptyFlexMessagingManager.swift
- swift-sdk/Internal/FlexMessagingManager.swift
- swift-sdk/Internal/FlexMessagingSerialization.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/IterableFlexMessage.swift
- swift-sdk/IterableFlexMessagingManagerProtocol.swift
- tests/flex-messaging-tests/FlexMessagingManager.swift
- tests/flex-messaging-tests/FlexMessagingManagerTests.swift
- tests/flex-messaging-tests/FlexMessagingSerializationTests.swift
* [MOB-5388](https://iterable.atlassian.net/browse/MOB-5388)
* provides functions to serialize to/from native data type and JSON payload
* changes schema to be `payload` instead of `custom`
[MOB-5388]: https://iterable.atlassian.net/browse/MOB-5388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5388] serialization

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-5701](https://iterable.atlassian.net/browse/MOB-5701)
[MOB-5701]: https://iterable.atlassian.net/browse/MOB-5701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5701] version 6.4.11

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/EmbeddedMessagingSerialization.swift
- swift-sdk/Internal/EmptyEmbeddedMessagingManager.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/IterableAPI.swift
- swift-sdk/IterableEmbeddedMessage.swift
- swift-sdk/IterableEmbeddedMessagingManagerProtocol.swift
* [MOB-5745](https://iterable.atlassian.net/browse/MOB-5745)
[MOB-5745]: https://iterable.atlassian.net/browse/MOB-5745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5745] rename to embedded messaging

- swift-sdk/Constants.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/RequestCreator.swift
- tests/unit-tests/InAppHelperTests.swift
* [MOB-5756](https://iterable.atlassian.net/browse/MOB-5756)
* creates route to messages endpoint
[MOB-5756]: https://iterable.atlassian.net/browse/MOB-5756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5756] create endpoint route

- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/EmbeddedMessagingSerialization.swift
- swift-sdk/Internal/EmptyEmbeddedMessagingManager.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/IterableEmbeddedMessage.swift
- swift-sdk/IterableEmbeddedMessagingManagerProtocol.swift
* [MOB-5774](https://iterable.atlassian.net/browse/MOB-5774)
* fix up some of our mapped data types for compatibility
* add some shims for incoming work
[MOB-5774]: https://iterable.atlassian.net/browse/MOB-5774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5774] data types

- swift-sdk/Constants.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/IterableConfig.swift
- tests/unit-tests/InAppHelperTests.swift
* [MOB-5757](https://iterable.atlassian.net/browse/MOB-5757)
* implements timer for automatic message fetching
[MOB-5757]: https://iterable.atlassian.net/browse/MOB-5757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5757] messages auto fetch timer

- swift-sdk/Internal/EmbeddedMessagingManager.swift
* [MOB-5758](https://iterable.atlassian.net/browse/MOB-5758)
* accounts for app state in fetch timer
[MOB-5758]: https://iterable.atlassian.net/browse/MOB-5758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5758] account for app state in message fetching timer

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/EmbeddedMessagingProcessor.swift
- tests/embedded-messaging-tests/EmbeddedMessagingManagerTests.swift
- tests/embedded-messaging-tests/EmbeddedMessagingProcessorTests.swift
* [MOB-5832](https://iterable.atlassian.net/browse/MOB-5832)
* adds the ability to add UI objects as a delegate for updated messages
[MOB-5832]: https://iterable.atlassian.net/browse/MOB-5832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5832] update delegate

- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/IterableAPI.swift
* [MOB-5741](https://iterable.atlassian.net/browse/MOB-5741)
* adds getter for auth token
[MOB-5741]: https://iterable.atlassian.net/browse/MOB-5741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5741] add way to read current auth token

- swift-sdk/Constants.swift
- swift-sdk/Internal/RequestCreator.swift
> remap JSON key

- swift-sdk/Internal/InternalIterableAPI.swift
* [MOB-5735](https://iterable.atlassian.net/browse/MOB-5735)
[MOB-5735]: https://iterable.atlassian.net/browse/MOB-5735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5736] allow setting auth token through identity

- swift-sdk/Internal/AuthManager.swift
* [MOB-5737](https://iterable.atlassian.net/browse/MOB-5737)
[MOB-5737]: https://iterable.atlassian.net/browse/MOB-5737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5737] schedule a default timer of 10s if auth token null

- swift-sdk/Internal/EmbeddedMessagingProcessor.swift
- swift-sdk/Internal/EmbeddedMessagingSerialization.swift
- swift-sdk/IterableEmbeddedMessage.swift
- tests/embedded-messaging-tests/EmbeddedMessagingManagerTests.swift
- tests/embedded-messaging-tests/EmbeddedMessagingProcessorTests.swift
* [MOB-5746](https://iterable.atlassian.net/browse/MOB-5746)
[MOB-5746]: https://iterable.atlassian.net/browse/MOB-5746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5746] payload fields

- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/EmbeddedMessagingSerialization.swift
- tests/embedded-messaging-tests/EmbeddedMessagingManagerTests.swift
- tests/unit-tests/InAppHelperTests.swift
> wrap embedded messages payload

- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/EmptyEmbeddedMessagingManager.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/IterableEmbeddedMessagingManagerProtocol.swift
- tests/embedded-messaging-tests/EmbeddedMessagingManagerTests.swift
* [MOB-5969](https://iterable.atlassian.net/browse/MOB-5969)
* stop manager from retrieving when logged out
* slight reorganization and clarity
[MOB-5969]: https://iterable.atlassian.net/browse/MOB-5969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5969] stop when logged out

- swift-sdk/Internal/EmbeddedMessagingManager.swift
* [MOB-5964](https://iterable.atlassian.net/browse/MOB-5964)
* retrieves on foregrounding of app
[MOB-5964]: https://iterable.atlassian.net/browse/MOB-5964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5964] foreground retrieval

- swift-sdk/Internal/EmbeddedMessagingManager.swift
* [MOB-5845](https://iterable.atlassian.net/browse/MOB-5845)
* doesn't start the automatic fetching timer if config's time is 0 or less
[MOB-5845]: https://iterable.atlassian.net/browse/MOB-5845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5845] auto fetch boundary

- swift-sdk/Constants.swift
* [MOB-5973](https://iterable.atlassian.net/browse/MOB-5973)
* renames the API used for message retrieval
* to be merged in when backend is ready
[MOB-5973]: https://iterable.atlassian.net/browse/MOB-5973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5973] route rename

- notification-extension/ITBNotificationServiceExtension.swift
* [PRO-7882](https://iterable.atlassian.net/browse/PRO-7882)
> Added the `ITBNotificationServiceExtensionDelegate`for the ability to handle rich push from another while still being able to display rich push through Iterable
[PRO-7882]: https://iterable.atlassian.net/browse/PRO-7882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added delegate that handles rich push from another provider

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-6110](https://iterable.atlassian.net/browse/MOB-6110)
[MOB-6110]: https://iterable.atlassian.net/browse/MOB-6110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6110] version 6.4.13 updates

- swift-sdk/IterableAPI.swift
> Version 6.5.0 alpha1

- swift-sdk/Internal/EmbeddedMessagingManager.swift
- tests/unit-tests/BlankApiClient.swift
* [MOB-6132](https://iterable.atlassian.net/browse/MOB-6132)
* adds a way to initiate a manual refresh by means of a UI action (pull down)
* temporary until we understand how to better integrate it with our SDK/API
[MOB-6132]: https://iterable.atlassian.net/browse/MOB-6132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6132] manual override refresh

- swift-sdk/Constants.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/EmbeddedMessagingProcessor.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- swift-sdk/Internal/RequestProcessorProtocol.swift
- tests/embedded-messaging-tests/EmbeddedMessagingManagerTests.swift
- tests/embedded-messaging-tests/EmbeddedMessagingProcessorTests.swift
- tests/unit-tests/BlankApiClient.swift
* [MOB-5391](https://iterable.atlassian.net/browse/MOB-5391)
* implements the path to calling message received events
* for now, we call on a custom event to stand in for tracking
[MOB-5391]: https://iterable.atlassian.net/browse/MOB-5391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5391] embedded message received tracking

- swift-sdk/Constants.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/EmbeddedMessagingProcessor.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- swift-sdk/Internal/RequestProcessorProtocol.swift
- tests/unit-tests/BlankApiClient.swift
* [MOB-5390](https://iterable.atlassian.net/browse/MOB-5390)
* adds the click tracking API for embedded messaging by means of custom event
[MOB-5390]: https://iterable.atlassian.net/browse/MOB-5390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5390] click event

- swift-sdk/Constants.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- swift-sdk/Internal/RequestProcessorProtocol.swift
- tests/embedded-messaging-tests/EmbeddedMessagingProcessorTests.swift
- tests/unit-tests/BlankApiClient.swift
* [MOB-6143](https://iterable.atlassian.net/browse/MOB-6143)
* implements API for embedded messaging's dismiss event through a custom event
[MOB-6143]: https://iterable.atlassian.net/browse/MOB-6143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6143] dismiss event

- swift-sdk/Constants.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- swift-sdk/Internal/RequestProcessorProtocol.swift
- tests/unit-tests/BlankApiClient.swift
* [MOB-6001](https://iterable.atlassian.net/browse/MOB-6001)
* adds the singular impression event API route for embedded messaging
[MOB-6001]: https://iterable.atlassian.net/browse/MOB-6001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6001] impression event

- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/EmbeddedMessagingProcessor.swift
- swift-sdk/Internal/EmbeddedMessagingSerialization.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/IterableEmbeddedMessage.swift
* [MOB-6187](https://iterable.atlassian.net/browse/MOB-6187)
This pull request renames message id throughout the SDK to match the change to the embedded message payload.
[MOB-6187]: https://iterable.atlassian.net/browse/MOB-6187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6187] change message id in payload

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Constants.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/EmbeddedSessionManager.swift
- swift-sdk/Internal/EmptyEmbeddedMessagingManager.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/MiscEmbeddedClasses.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/OnlineRequestProcessor.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/Internal/RequestHandler.swift
- swift-sdk/Internal/RequestHandlerProtocol.swift
- swift-sdk/Internal/RequestProcessorProtocol.swift
- swift-sdk/IterableAPI.swift
- swift-sdk/IterableEmbeddedMessagingManagerProtocol.swift
- tests/unit-tests/BlankApiClient.swift
* [MOB-6255](https://iterable.atlassian.net/browse/MOB-6255)
This PR creates an embedded message session that the app can use to manage impression tracking. The SDK handles the API calls and payload, but the app needs to still handle the impression tracking via SDK methods.
[MOB-6255]: https://iterable.atlassian.net/browse/MOB-6255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6255] Embedded Impression Session

- swift-sdk/Constants.swift
- tests/unit-tests/IterableAPITests.swift
* [MOB-6284](https://iterable.atlassian.net/browse/MOB-6284)
This pull request fixes the incorrect endpoints.
[MOB-6284]: https://iterable.atlassian.net/browse/MOB-6284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6284] endpoint fixes

- swift-sdk/Internal/EmbeddedMessagingManager.swift
* [MOB-6112](https://iterable.atlassian.net/browse/MOB-6112)
> Reset auto fetch timer to 0. And stop current timer when subscription inactive or invalid API key to avoid unnecessary automatic em calls
[MOB-6112]: https://iterable.atlassian.net/browse/MOB-6112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6112] - Feature flagging

- swift-sdk/Constants.swift
- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/EmbeddedMessagingProcessor.swift
- swift-sdk/Internal/EmbeddedMessagingSerialization.swift
- swift-sdk/Internal/EmbeddedSessionManager.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/IterableEmbeddedMessage.swift
- swift-sdk/IterableEmbeddedMessagingUpdateDelegate.swift
- tests/embedded-messaging-tests/EmbeddedMessagingManagerTests.swift
- tests/embedded-messaging-tests/EmbeddedMessagingProcessorTests.swift
* [MOB-6360](https://iterable.atlassian.net/browse/MOB-6360)
This PR lets app know when embedded messaging is no longer available via protocol method
[MOB-6360]: https://iterable.atlassian.net/browse/MOB-6360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6360] Protocol method invalid subscription

- .github/workflows/e2e.yml
- swift-sdk/Internal/RequestCreator.swift
- tests/endpoint-tests/CI.swift.template
- tests/endpoint-tests/EndpointTests.swift
- tests/endpoint-tests/Environment.swift
- tests/endpoint-tests/IterableAPISupport.swift
- tests/endpoint-tests/scripts/env_vars.sh.sample
- tests/endpoint-tests/scripts/run_test.sh
This PR should fix integration tests in conjunction with new repo env vars via github secrets.
> Fix integration test

- tests/unit-tests/InboxTests.swift
> fixes testRemove unit test in inbox tests.
> fixes testRemove unit test

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-6480](https://iterable.atlassian.net/browse/MOB-6480)
> Releasing 6.4.14
[MOB-6480]: https://iterable.atlassian.net/browse/MOB-6480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB - 6480] - Prepare for release 6.4.14

- swift-sdk/IterableEmbeddedMessage.swift
Change campaignId type in IterableEmbeddedMessage to Int.
> update campaign id type

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-6660](https://iterable.atlassian.net/browse/MOB-6660)
This pull request prepares for the version 6.4.15 release.
> [MOB-6660] prepares for 6.4.15 release

- swift-sdk/Constants.swift
- swift-sdk/Internal/EmbeddedSessionManager.swift
- swift-sdk/Internal/MiscEmbeddedClasses.swift
* [MOB-7219](https://iterable.atlassian.net/browse/MOB-7219)
> This pull request updates the path for the session tracking endpoint to align with the backend. It seems like we have a redundant endpoint for impression tracking that needs to be revisited.
[MOB-7219]: https://iterable.atlassian.net/browse/MOB-7219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7219] impressions tracking rework

- swift-sdk/Internal/RequestProcessorUtil.swift
> Retry mechanism for failed JWT related errors

- swift-sdk/Internal/NetworkHelper.swift
- tests/unit-tests/IterableAPIResponseTests.swift
> Add retry mechanism to the iOS SDK for failed network requests

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-7285](https://iterable.atlassian.net/browse/MOB-7285)
> This pull request prepares for the 6.4.16 release.
[MOB-7285]: https://iterable.atlassian.net/browse/MOB-7285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7285] prepare for 6.4.16

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/DependencyContainerProtocol.swift
- swift-sdk/Internal/EmbeddedHelper.swift
- swift-sdk/Internal/IterableEmbeddedManager.swift
- tests/unit-tests/EmbeddedManagerTests.swift
* [MOB-7316](https://iterable.atlassian.net/browse/MOB-7316)
> This pull request sets up custom action handling logic in handleEmbeddedClick.
[MOB-7316]: https://iterable.atlassian.net/browse/MOB-7316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7316] sets up custom action handling

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/EmbeddedMessagingProcessor.swift
- swift-sdk/Internal/EmptyEmbeddedManager.swift
- swift-sdk/Internal/IterableEmbeddedManager.swift
- swift-sdk/IterableEmbeddedManagerProtocol.swift
- tests/unit-tests/EmbeddedManagerTests.swift
- tests/unit-tests/EmbeddedMessagingProcessorTests.swift
* [MOB-6734](https://iterable.atlassian.net/browse/MOB-6734)
* [MOB-6639](https://iterable.atlassian.net/browse/MOB-6639)
> This PR implements placements [MOB-6734] and a new helper method to resolve image data [MOB-6639]. Message order is maintained after asynchronously obtaining the image data. Also updates tests to work with new changes.
[MOB-6734]: https://iterable.atlassian.net/browse/MOB-6734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-6639]: https://iterable.atlassian.net/browse/MOB-6639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-6734]: https://iterable.atlassian.net/browse/MOB-6734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> [MOB-6734] [MOB-6639] Implement placements and resolveMessages()

- swift-sdk/uicomponents/IterableEmbeddedView.swift
* [MOB-7475](https://iterable.atlassian.net/browse/MOB-7475)
[MOB-7475]: https://iterable.atlassian.net/browse/MOB-7475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7475] updates button naming to primary and secondary

- swift-sdk/uicomponents/IterableEmbeddedView.swift
* [MOB-7474](https://iterable.atlassian.net/browse/MOB-7474)
> This pull request creates a configure function that properly uses default values based on view type.
[MOB-7474]: https://iterable.atlassian.net/browse/MOB-7474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7474] updates configuration to properly use default values

- swift-sdk/uicomponents/IterableEmbeddedView.swift
* [MOB-7487](https://iterable.atlassian.net/browse/MOB-7487)
> This pull request adds logic to the click handling to deal with the differences in url handling vs. custom action handling.
[MOB-7487]: https://iterable.atlassian.net/browse/MOB-7487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7487] ootb custom action handling

- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
* [MOB-7490](https://iterable.atlassian.net/browse/MOB-7490)
run github workflow to create tag and assets for `6.4.17`
[MOB-7490]: https://iterable.atlassian.net/browse/MOB-7490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7490] 6.4.17 release with tags and assets

- swift-sdk/uicomponents/IterableEmbeddedView.swift
* [MOB-7531](https://iterable.atlassian.net/browse/MOB-7531)
Updated code to ensure it passes `pod lib lint`
[MOB-7531]: https://iterable.atlassian.net/browse/MOB-7531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7531] fix iOS SDK embedded pod lint

- swift-sdk/Internal/IterableEmbeddedManager.swift
- swift-sdk/IterableEmbeddedMessage.swift
- swift-sdk/uicomponents/IterableEmbeddedView.swift
* [MOB-7576](https://iterable.atlassian.net/browse/MOB-7576)
> This pull request adds accessibility label to the resolved message class. Also, updates embedded message class to have a mediaUrlCaption that is passed from the platform.
[MOB-7576]: https://iterable.atlassian.net/browse/MOB-7576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7576] adds accessibility label to resolved message class

- sample-apps/swift-sample-app/swift-sample-app/AppDelegate.swift
- swift-sdk/Internal/IterableEmbeddedManager.swift
- swift-sdk/uicomponents/IterableEmbeddedView.swift
* [MOB-7565](https://iterable.atlassian.net/browse/MOB-7565)
> This pull request includes refactoring for the `IterableEmbeddedView`. The `IterableEmbeddedView` now takes in the message and does the setting of view elements internally. The `IterableEmbeddedView` elements are also renamed to align with Android SDK naming. Pulling the image processing into the `IterableEmbeddedView` class and removing the `resolveMessages` function will be tackled on a separate PR.
[MOB-7565]: https://iterable.atlassian.net/browse/MOB-7565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7565] OOTB view refactoring

- swift-sdk/Constants.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/DependencyContainerProtocol.swift
- swift-sdk/Internal/IterableEmbeddedManager.swift
- swift-sdk/Internal/IterableUserDefaults.swift
- swift-sdk/Internal/LocalStorage.swift
- swift-sdk/Internal/LocalStorageProtocol.swift
- swift-sdk/Internal/RequestCreator.swift
- tests/common/MockLocalStorage.swift
- tests/unit-tests/BlankApiClient.swift
- tests/unit-tests/EmbeddedManagerTests.swift
* [MOB-7468](https://iterable.atlassian.net/browse/MOB-7468)
> We have updated the parameter to support the retrieval of only new messages for the embedded functionality.
> We have updated the related test cases.
[MOB-7468]: https://iterable.atlassian.net/browse/MOB-7468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7468] updated payload reflecting only new messages

- swift-sdk/Internal/EmptyEmbeddedManager.swift
- swift-sdk/Internal/IterableEmbeddedManager.swift
- swift-sdk/IterableEmbeddedManagerProtocol.swift
* [MOB-7663](https://iterable.atlassian.net/browse/MOB-7663)
> This pull request removes resolved messages and associated functionality.
[MOB-7663]: https://iterable.atlassian.net/browse/MOB-7663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7663] removes resolved messages

- swift-sdk/Internal/IterableEmbeddedManager.swift
* [MOB-7673](https://iterable.atlassian.net/browse/MOB-7673)
Updates the content regardless of new messages. Fixes issue with fetch on app foreground.
[MOB-7673]: https://iterable.atlassian.net/browse/MOB-7673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Mob 7673 Fixes issue with updating embedded content

- sample-apps/swift-sample-app/swift-sample-app/EmbeddedMessages/EmbeddedMessagesViewController.swift
- swift-sdk/Resources/IterableEmbeddedView.xib
- swift-sdk/uicomponents/IterableEmbeddedView.swift
* [MOB-7679](https://iterable.atlassian.net/browse/MOB-7679)
> Updates OOTB constraints
[MOB-7679]: https://iterable.atlassian.net/browse/MOB-7679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7679] Updates OOTB constraints

- swift-sdk/Resources/IterableEmbeddedView.xib
- swift-sdk/uicomponents/IterableEmbeddedView.swift
* [MOB-7697](https://iterable.atlassian.net/browse/MOB-7697)
> Fixes some of the bugs introduced during GA Bug bash
[MOB-7697]: https://iterable.atlassian.net/browse/MOB-7697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Finalizing constraints 2

- CHANGELOG.md
* [MOB-6114](https://iterable.atlassian.net/browse/MOB-6114)
> Prepare for 6.5.0
[MOB-6114]: https://iterable.atlassian.net/browse/MOB-6114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB - 6114] - Prepare for 6.5.0

- swift-sdk/Internal/AuthManager.swift
- tests/unit-tests/AuthTests.swift
* [MOB-7795](https://iterable.atlassian.net/browse/MOB-7795)
> We have removed JWT token generation while user not logged in.
[MOB-7795]: https://iterable.atlassian.net/browse/MOB-7795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove JWT token generation if user not logged in

- swift-sdk/Internal/InternalIterableAppIntegration.swift
* [MOB-8038](https://iterable.atlassian.net/browse/MOB-8038)
Updates logic for notificationsEnabled flag to be more inclusive in case of failures for fetching the current settings.
[MOB-8038]: https://iterable.atlassian.net/browse/MOB-8038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-8038] Changed authorizationStatus check for notificationsEnabled Flag

- swift-sdk/IterableAPI.swift
This pull request removes the last push payload setter since it is set internally and we don't wanna make this public without a specific use case.
> removes last push payload setter

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-8132](https://iterable.atlassian.net/browse/MOB-8132)
> Prepare for iOS SDK version 6.5.1 release
[MOB-8132]: https://iterable.atlassian.net/browse/MOB-8132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB - 8132] - Prepare for 6.5.1

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-8232](https://iterable.atlassian.net/browse/MOB-8232)
> Prepare for 6.5.2
[MOB-8232]: https://iterable.atlassian.net/browse/MOB-8232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-8232] - Prepare for 6.5.2

- .github/workflows/build-and-test.yml
- .github/workflows/e2e.yml
- .github/workflows/ios-sdk-release.yml
* [MOB-8328](https://iterable.atlassian.net/browse/MOB-8328)
Address security issue: https://iterable.atlassian.net/browse/ISRR-529
Took the latest stable release commit SHA and replaced with insecure tags.
[MOB-8328]: https://iterable.atlassian.net/browse/MOB-8328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-8328] - use secure commit SHA in actions

- .gitignore
- swift-sdk/Constants.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/EmbeddedMessagingProcessor.swift
- swift-sdk/Internal/IterableEmbeddedManager.swift
- swift-sdk/Internal/IterableRequestUtil.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/IterableEmbeddedMessage.swift
- tests/unit-tests/BlankApiClient.swift
- tests/unit-tests/EmbeddedMessagingProcessorTests.swift
* [MOB-7647](https://iterable.atlassian.net/browse/MOB-7647)
[MOB-7647]: https://iterable.atlassian.net/browse/MOB-7647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB 6920/7647] - Diff merge

- .github/workflows/build-and-test.yml
- .github/workflows/e2e.yml
* [MOB-8423](https://iterable.atlassian.net/browse/MOB-8423)
> Bump YML Xcode version
[MOB-8423]: https://iterable.atlassian.net/browse/MOB-8423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-8423] - Set macos-12 to fix YML

- .gitignore
- Iterable-iOS-SDK.podspec
- swift-sdk.xcodeproj/xcshareddata/xcschemes/swift-sdk.xcscheme
- swift-sdk/Internal/InAppCalculations.swift
- swift-sdk/Internal/NetworkConnectivityManager.swift
- swift-sdk/Internal/NetworkMonitor.swift
- swift-sdk/IterableInboxNavigationViewController.swift
- tests/offline-events-tests/NetworkConnectivityManagerTests.swift
- tests/offline-events-tests/TaskRunnerTests.swift
* [MOB-8377](https://iterable.atlassian.net/browse/MOB-8377)
> Bump min iOS version to 12
[MOB-8377]: https://iterable.atlassian.net/browse/MOB-8377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB - 8377] - Bump min iOS version to 12

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-8611](https://iterable.atlassian.net/browse/MOB-8611)
> Prepare for 6.5.3
[MOB-8611]: https://iterable.atlassian.net/browse/MOB-8611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-8611] - Prepare for 6.5.3

- Gemfile.lock
* [MOB-8637](https://iterable.atlassian.net/browse/MOB-8637)
[MOB-8637]: https://iterable.atlassian.net/browse/MOB-8637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-8637] add platform arm64-darwin-22

- swift-sdk/Internal/AnonymousUserManager+Functions.swift
* [MOB-8929](https://iterable.atlassian.net/browse/MOB-8929)
[MOB-8929]: https://iterable.atlassian.net/browse/MOB-8929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bug fixes with double values having trailing zeros

- .gitignore
- CHANGELOG.md
- Gemfile.lock
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk.xcodeproj/xcshareddata/xcschemes/swift-sdk.xcscheme
- swift-sdk/Constants.swift
- swift-sdk/Internal/AuthManager.swift
- swift-sdk/Internal/DependencyContainerProtocol.swift
- swift-sdk/Internal/InAppCalculations.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/NetworkConnectivityManager.swift
- swift-sdk/Internal/NetworkHelper.swift
- swift-sdk/Internal/NetworkMonitor.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/RequestProcessorUtil.swift
- swift-sdk/IterableAPI.swift
- swift-sdk/IterableAuthManagerProtocol.swift
- swift-sdk/IterableConfig.swift
- swift-sdk/IterableInboxNavigationViewController.swift
- swift-sdk/RetryPolicy.swift
- tests/common/MockAuthManager.swift
- tests/offline-events-tests/NetworkConnectivityManagerTests.swift
- tests/offline-events-tests/TaskRunnerTests.swift
- tests/unit-tests/AuthTests.swift
- tests/unit-tests/IterableAPIResponseTests.swift
* [MOB-7981](https://iterable.atlassian.net/browse/MOB-7981)
[MOB-7981]: https://iterable.atlassian.net/browse/MOB-7981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Jwt improvement part1

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-9030](https://iterable.atlassian.net/browse/MOB-9030)
> Prepare for 6.5.4
[MOB-9030]: https://iterable.atlassian.net/browse/MOB-9030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9030] - Prepare for 6.5.4

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/AuthFailure.swift
- swift-sdk/AuthFailureReason.swift
- swift-sdk/Internal/AuthManager.swift
- swift-sdk/Internal/IterableUtil.swift
- swift-sdk/Internal/RequestProcessorUtil.swift
- swift-sdk/IterableAuthManagerProtocol.swift
- swift-sdk/IterableConfig.swift
- tests/common/MockAuthManager.swift
- tests/unit-tests/AuthTests.swift
* [MOB-7980](https://iterable.atlassian.net/browse/MOB-7980)
[MOB-7980]: https://iterable.atlassian.net/browse/MOB-7980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Jwt improvement part2

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-9248](https://iterable.atlassian.net/browse/MOB-9248)
> Prepare for 6.5.5
[MOB-9248]: https://iterable.atlassian.net/browse/MOB-9248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9248] - Prepare for 6.5.5

- swift-sdk/Internal/DeepLinkManager.swift
This is a pull request to fix #592 
I have manually verified it fixes the issue still present  in 6.5.4
> Fix iterable SDK bug #592

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-9385](https://iterable.atlassian.net/browse/MOB-9385)
[MOB-9385]: https://iterable.atlassian.net/browse/MOB-9385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9385] - Prepare for 6.5.6

- swift-sdk/Internal/AnonymousUserManager+Functions.swift
* [MOB-9309](https://iterable.atlassian.net/browse/MOB-9309)
> Resolve issue for nested object criteria match.
> Go to AUTTesting and try to match criteria which has '.' in field. like (saved_cars.color)
[MOB-9309]: https://iterable.atlassian.net/browse/MOB-9309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve nested criteria match issue

- swift-sdk/Internal/InternalIterableAPI.swift
* [MOB-9349](https://iterable.atlassian.net/browse/MOB-9349)
* [MOB-9302](https://iterable.atlassian.net/browse/MOB-9302)
> This pull request refactors the setEmail and setUserId functions to align with Android. Also, adds checks for AUT being enabled in order to allow for merging and replaying of events.
[MOB-9349]: https://iterable.atlassian.net/browse/MOB-9349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-9302]: https://iterable.atlassian.net/browse/MOB-9302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9349] disabling merging and replay when AUT is disabled

- swift-sdk/Internal/AnonymousUserManager.swift
* [MOB-9304](https://iterable.atlassian.net/browse/MOB-9304)
> Replayed events don't have proper createdAt timestamp
[MOB-9304]: https://iterable.atlassian.net/browse/MOB-9304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-9304 Replayed events don't have proper createdAt timestamp

- swift-sdk/Internal/AnonymousUserMerge.swift
- swift-sdk/Internal/DependencyContainerProtocol.swift
- swift-sdk/Internal/InternalIterableAPI.swift
* [MOB-9421](https://iterable.atlassian.net/browse/MOB-9421)
> This pull request makes tryMergeUser private and updates tryMergeUser to only take in an anonymous user as the source user id.
[MOB-9421]: https://iterable.atlassian.net/browse/MOB-9421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9421] make tryMergeUser private

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/AnonymousUserManager+Functions.swift
- tests/unit-tests/NestedFieldSupportForArrayData.swift
* [MOB-9309](https://iterable.atlassian.net/browse/MOB-9309)
> Support nested field types
>Video attached to the ticket, See a JIRA ticket for the video
[MOB-9309]: https://iterable.atlassian.net/browse/MOB-9309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-9309 Support nested field types

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-9549](https://iterable.atlassian.net/browse/MOB-9549)
> Prepare for 6.5.7
[MOB-9549]: https://iterable.atlassian.net/browse/MOB-9549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9549] Prepare for 6.5.7

- swift-sdk/Internal/AnonymousUserManager+Functions.swift
- tests/unit-tests/IsOneOfInNotOneOfCriteareaTest.swift
* [MOB-9518](https://iterable.atlassian.net/browse/MOB-9518)
> isNotOneOf criteria is causing a crash
[MOB-9518]: https://iterable.atlassian.net/browse/MOB-9518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> isNotOneOf criteria is causing a crash

- swift-sdk/Constants.swift
- swift-sdk/Internal/AnonymousUserManager+Functions.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- tests/unit-tests/AnonymousUserComplexCriteriaMatchTests.swift
- tests/unit-tests/AnonymousUserCriteriaIsSetTests.swift
- tests/unit-tests/AnonymousUserCriteriaMatchTests.swift
- tests/unit-tests/CombinationLogicEventTypeCriteria.swift
- tests/unit-tests/ComparatorDataTypeWithArrayInput.swift
- tests/unit-tests/ComparatorTypeDoesNotEqualMatchTest.swift
- tests/unit-tests/DataTypeComparatorSearchQueryCriteria.swift
- tests/unit-tests/IsOneOfInNotOneOfCriteareaTest.swift
- tests/unit-tests/NestedFieldSupportForArrayData.swift
- tests/unit-tests/UserMergeScenariosTests.swift
* [MOB-9584](https://iterable.atlassian.net/browse/MOB-9584)
> This pull request renames "criterias" to "criteriaSets".
[MOB-9584]: https://iterable.atlassian.net/browse/MOB-9584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9584] changes "criterias" to "criteriaSets"

- sample-apps/objc-sample-app/objc-sample-app/AppDelegate.m
- sample-apps/objc-sample-app/objc-sample-app/objc-sample-app.entitlements
- sample-apps/swift-sample-app/swift-sample-app.xcodeproj/project.pbxproj
- sample-apps/swift-sample-app/swift-sample-app/AppDelegate.swift
- sample-apps/swift-sample-app/swift-sample-app/swift-sample-app.entitlements
* [MOB-9622](https://iterable.atlassian.net/browse/MOB-9622)
🗑️ Removed Iterable specific identifiers and hardcoded URLs to use generic ones instead on the sample app.
[MOB-9622]: https://iterable.atlassian.net/browse/MOB-9622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9622] Sample App code cleanup

- sample-apps/swift-sample-app/swift-sample-app/AppDelegate.swift
- swift-sdk/Internal/AnonymousUserManager.swift
- swift-sdk/IterableConfig.swift
* [MOB-9637](https://iterable.atlassian.net/browse/MOB-9637)
Description
> add handlers for notifying customer app of newly created anon userid
[MOB-9637]: https://iterable.atlassian.net/browse/MOB-9637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-9637 add handlers for notifying customer app of newly created anon userid

- swift-sdk/Internal/AnonymousUserManager+Functions.swift
- tests/unit-tests/NestedFieldSupportForArrayData.swift
* [MOB-6272](https://iterable.atlassian.net/browse/MOB-6272)
> Add support for Nested JSON with Array Criteria Match
[MOB-6272]: https://iterable.atlassian.net/browse/MOB-6272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add support for Nested JSON with Array Criteria Match

- swift-sdk.xcodeproj/project.pbxproj
- tests/unit-tests/CombinationComplexCriteria.swift
* [MOB-9310](https://iterable.atlassian.net/browse/MOB-9310)
> Write automated unit tests against Complex criteria
[MOB-9310]: https://iterable.atlassian.net/browse/MOB-9310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Write automated unit tests against Complex criteria

- sample-apps/swift-sample-app/swift-sample-app/Base.lproj/Main.storyboard
- sample-apps/swift-sample-app/swift-sample-app/CoffeeListTableViewController.swift
- swift-sdk/Constants.swift
- swift-sdk/Internal/AnonymousUserManager.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/IterableUserDefaults.swift
- swift-sdk/Internal/LocalStorage.swift
- swift-sdk/Internal/LocalStorageProtocol.swift
- swift-sdk/IterableAPI.swift
- tests/common/MockLocalStorage.swift
* [MOB-9677](https://iterable.atlassian.net/browse/MOB-9677)
> Keep AUT off until consent to track has been granted
[MOB-9677]: https://iterable.atlassian.net/browse/MOB-9677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Keep AUT off until consent to track has been granted

- swift-sdk/Internal/AnonymousUserManager.swift
* [MOB-9699](https://iterable.atlassian.net/browse/MOB-9699)
> This pull request adds a log indicating consent is not given.
[MOB-9699]: https://iterable.atlassian.net/browse/MOB-9699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9699] adds consent log statement

- swift-sdk/Internal/AnonymousUserManager.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/IterableAPI.swift
* [MOB-9699](https://iterable.atlassian.net/browse/MOB-9699)
> This pull request adds additional logging for testing purposes.
[MOB-9699]: https://iterable.atlassian.net/browse/MOB-9699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9699] adds additional logging

- swift-sdk/Internal/InternalIterableAPI.swift
* [MOB-9751](https://iterable.atlassian.net/browse/MOB-9751)
> This pull request adds a check for AUT enablement and updates the logging for it.
[MOB-9751]: https://iterable.atlassian.net/browse/MOB-9751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9751] adds check for anon tracking enablement and updates logging

- swift-sdk/Constants.swift
- swift-sdk/Internal/AnonymousUserManager.swift
- swift-sdk/Internal/AuthManager.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/IterableUserDefaults.swift
- swift-sdk/Internal/LocalStorage.swift
- swift-sdk/Internal/LocalStorageProtocol.swift
- tests/common/MockLocalStorage.swift
* [MOB-9996](https://iterable.atlassian.net/browse/MOB-9996)
> This pull request separates the user update object in local storage to prevent user updates from being lost. This also simplifies a lot of the event processing code.
[MOB-9996]: https://iterable.atlassian.net/browse/MOB-9996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9996] User update rearchitecting

- swift-sdk/Internal/AnonymousUserManager.swift
* [MOB-10055](https://iterable.atlassian.net/browse/MOB-10055)
> This pull request renames createKnownUserIfCriteriaMatched to createAnonymousUser.
[MOB-10055]: https://iterable.atlassian.net/browse/MOB-10055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10055] updates method naming

- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/IterableAPI.swift
* [MOB-9946](https://iterable.atlassian.net/browse/MOB-9946)
> Add auth checks for api call methods
[MOB-9946]: https://iterable.atlassian.net/browse/MOB-9946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-9946 Add auth checks for api call methods

- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/IterableAPI.swift
* [MOB-10089](https://iterable.atlassian.net/browse/MOB-10089)
> This pull request renames the consent setting function to setVisitorUsageTracked.
[MOB-10089]: https://iterable.atlassian.net/browse/MOB-10089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10089] renaming to setVisitorUsageTracked

- swift-sdk/Internal/InAppManager+Functions.swift
- swift-sdk/Internal/ThreadSafeOrderedDictionary.swift
https://iterable.atlassian.net/browse/MOB-10319
Converted the normal lock to a ns recursive lock to avoid deadlocks
> [MOB-10319] Recursive lock for dictionary wrapper for safety reasons

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-10367](https://iterable.atlassian.net/browse/MOB-10367)
> This pull request prepares for 6.6.0-beta2 release.
[MOB-10367]: https://iterable.atlassian.net/browse/MOB-10367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10367] update pointers and changelog

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-10310](https://iterable.atlassian.net/browse/MOB-10310)
> This pull request includes changes to pointers and changelog for the release of the version 6.5.8 beta.
[MOB-10310]: https://iterable.atlassian.net/browse/MOB-10310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10310] updates pointers and changelog

- fastlane/Fastfile
> This pull request updates repo name in fastlane script.
> [MOB-XXXX] renames sdk repo in script

- tests/unit-tests/InAppTests.swift
> [MOB-9233] Fix tests for iOS (and make them match android)

- .github/workflows/build-and-test.yml
- .github/workflows/e2e.yml
- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/SDK/IterableAPI.swift
* [MOB-10605](https://iterable.atlassian.net/browse/MOB-10605)
> This pull request prepares the version 6.5.9 release.
[MOB-10605]: https://iterable.atlassian.net/browse/MOB-10605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10605] prepares version 6.5.9 release

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/SDK/IterableAPI.swift
* [MOB-10652](https://iterable.atlassian.net/browse/MOB-10652)
> This pull request prepares for the version 6.5.10 release.
[MOB-10652]: https://iterable.atlassian.net/browse/MOB-10652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10652] prepares for version 6.5.10 release

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/SDK/IterableAPI.swift
* [MOB-10709](https://iterable.atlassian.net/browse/MOB-10709)
> This pull request prepares version 6.5.11 release.
[MOB-10709]: https://iterable.atlassian.net/browse/MOB-10709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10709] prepares for version 6.5.11 release

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Core/Constants.swift
- swift-sdk/Internal/AnonymousUserManager.swift
- swift-sdk/Internal/AnonymousUserManagerProtocol.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/SDK/IterableConfig.swift
- tests/unit-tests/IterableApiCriteriaFetchTests.swift
* [MOB-10616](https://iterable.atlassian.net/browse/MOB-10616)
Reduce the lag time between criteria updates and evaluations for mobile users, ensuring timely updates in alignment with marketer-defined criteria. 
[MOB-10616]: https://iterable.atlassian.net/browse/MOB-10616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10616] Improve Criteria Update Frequency

- README.md
* [DOCS-4993](https://iterable.atlassian.net/browse/DOCS-4993)
Removed link to beta disclaimer.
[DOCS-4993]: https://iterable.atlassian.net/browse/DOCS-4993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DOCS-4993] Removed beta disclaimer link

- .github/workflows/prepare-for-release.yml
- .gitignore
- CHANGELOG.md
* [MOB-10788](https://iterable.atlassian.net/browse/MOB-10788)
> Adding Changelog section for unreleased section which the automation will be using. Gitigonre to ignore debug file
yml similar to android release which follows the Iterable release doc.
[MOB-10788]: https://iterable.atlassian.net/browse/MOB-10788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10788] - Github Action Pre Release

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/SDK/IterableAPI.swift
* [MOB-10929](https://iterable.atlassian.net/browse/MOB-10929)
> This pull request prepares for version 3.6.0-beta3 release.
[MOB-10929]: https://iterable.atlassian.net/browse/MOB-10929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10929] updates changelog and version numbers

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
* [MOB-11635](https://iterable.atlassian.net/browse/MOB-11635)
Better Issue template to add clarity to the Issue reporting process
[MOB-11635]: https://iterable.atlassian.net/browse/MOB-11635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-11635 Improve Issue Templates

- swift-sdk/Internal/Utilities/IterableUtil.swift
**Ticket**: [MOB-11622](https://iterable.atlassian.net/issues/MOB-11622?filter=-1)
Washington Post is unable to control the window of an InApp message on iOS SDK. InApp messages are not displaying in the active window when using iPad Stage Manager or multi-window scenarios.
- **Project**: Sandbox (ID: 26717)
- **Organization ID**: 3516  
- **iOS SDK Version**: 6.5.11
- **Campaign**: https://boss.prd-itbl.co/campaigns/13299557?view=Summary
- **ARR**: 710,022 (strategic account)
Current SDK window detection logic fails with Stage Manager:
- Uses `AppExtensionHelper.application?.delegate?.window??.rootViewController` (returns nil on multi-window)
- Falls back to `AppExtensionHelper.application?.windows.first?.rootViewController` (wrong window)
Enhanced window detection to find active window …
> MOB-11622: Fix InApp messages displaying in wrong window with Stage Manager

- swift-sdk/Core/Constants.swift
> This pull request renames "anonSessionContext" to "unknownSessionContext" to align with BE updates.
> [MOB-XXXX] rename anon session context
