- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- README.md
Update release number.
Change the links in README.md file to point to GitHub. (This is so that it looks right when viewed from cocoapods.org).
> First Swift SDK Release 6.0.0.

- README.md
- Created a section for "Installing with a dependency manager", and put both the CocoaPods and the Carthage sections there
- Clarified the Carthage and the CocoaPods instructions a bit (reorganized some steps, updated text, etc)
> Updates for Carthage/CocoaPods instructions

- swift-sdk/Internal/IterableAPIInternal.swift
Currently, I see messages being logged as:
```
registerToken failed:, Unable to find a push integration set up for application 
iOSStaging on APNS_SANDBOX, got response 126 bytes
```
This change should make them appear as:
```
registerToken failed:, Unable to find a push integration set up for application 
iOSStaging on APNS_SANDBOX, got response "{\"msg\":\"Unable to find a 
push integration set up for application iOSStaging on 
APNS_SANDBOX\",\"code\":\"BadParams\",\"params\":null}"
```
> Log NSData as human readable string

- swift-sdk/IterableInboxCell.swift
- swift-sdk/IterableInboxNavigationViewController.swift
- swift-sdk/IterableInboxViewController.swift
Final touches for inbox customization.
1. consistent naming of xib vs nib
2. initialize protocol in better way
3. expose Xcode inspectable properties for IterableInboxViewController.
> [MOB-962] - inbox customization 6

- Tests/swift-sdk-swift-tests/InboxViewControllerViewModelTests.swift
- swift-sdk/Internal/InboxViewControllerViewModel.swift
- swift-sdk/IterableInboxViewController.swift
We can have multiple sections now so we should look at index path instead of row index.
> [MOB-1096] - Use indexPath instead of rowIndex.

- swift-sdk.xcodeproj/project.pbxproj
We can always run `swiftormat .` from the command line. This is causing Xcode issues. I am seeing "code was modified outside" messages often. Also I think this may be impacting code highlighting. 
Plus we should have separate PRs for formatting related issues.
> Remove build step run swiftformat

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Constants.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/Auth.swift
- swift-sdk/Internal/DataFieldsHelper.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/LocalStorageProtocol.swift
- swift-sdk/Internal/UserDefaultsLocalStorage.swift
- swift-sdk/IterableAPI.swift
- tests/swift-sdk-swift-tests/AuthTests.swift
- tests/swift-sdk-swift-tests/DeferredDeepLinkTests.swift
- tests/swift-sdk-swift-tests/InboxTests.swift
- tests/swift-sdk-swift-tests/IterableAPIResponseTests.swift
- tests/swift-sdk-swift-tests/IterableAPITests.swift
- tests/swift-sdk-swift-tests/RequestCreatorTests.swift
This PR adds a way to let our customers use authentication tokens (like [JWT](https://jwt.io/)) be used with our SDK. This is done by:
- adding a new `setEmail`/`setUserId` function that not only does the same thing as `IterableAPI.email = "email address"`/`IterableAPI.userId = "user ID"` but also adds an optional field to set the user's token (which our customers will generate/handle). This does mean that calling the function is the only way to set the token. I made this choice to avoid possible race conditions with setting properties, and because I think it's a better formalized way to use our SDK.
- adding the token to API calls if it's present
This PR also has some minor refactoring just for organizational purposes.
> [MOB-1775] add way for auth token to be included

- swift-sdk/Constants.swift
- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/IterableAPIInternal.swift
- swift-sdk/Internal/LocalStorageProtocol.swift
- swift-sdk/Internal/Models.swift
- swift-sdk/Internal/UserDefaultsLocalStorage.swift
- tests/common/CommonMocks.swift
- tests/swift-sdk-swift-tests/foundational-tests/LocalStorageTests.swift
* [MOB-2529](https://iterable.atlassian.net/browse/MOB-2529)
> We now persist feature flag values (currently SDKofflineMode and SDKOfflineModeBeta) coming back from server. If the network is offline we use the persisted values.
> [MOB-2529] - Persist previous feature state locally.

- swift-sdk/Internal/InAppCalculations.swift
- swift-sdk/Internal/InAppContentParser.swift
- swift-sdk/Internal/InAppDisplayer.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/IterableHtmlMessageViewController.swift
- swift-sdk/IterableMessaging.swift
- tests/swift-sdk-swift-tests/in-app-tests/InAppParsingTests.swift
- ui-tests-app/ViewController.swift
* [MOB-2216](https://iterable.atlassian.net/browse/MOB-2216)
> Instead of relying on UIEdgeInsets for padding we are now using a proper strongly typed Padding struct to parse padding internally.
> [MOB-2216] - Strongly typed padding struct instead of UIEdgeInsets.

- tests/common/CommonExtensions.swift
- tests/common/CommonMocks.swift
- tests/offline-events-tests/TaskProcessorTests.swift
- tests/swift-sdk-swift-tests/IterableAPITests.swift
- tests/swift-sdk-swift-tests/RegistrationTests.swift
- tests/swift-sdk-swift-tests/in-app-tests/InAppTests.swift
* [MOB-2523](https://iterable.atlassian.net/browse/MOB-2523)
> Removed method `getLastRequestBody`. This was using hard coded last request instead of getting the specific request for an endpoint.
> [MOB-2523] - Replace getLastRequestBody with less error prone request callback.

- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/Promise.swift
- tests/common/CommonExtensions.swift
- tests/common/CommonMocks.swift
- tests/offline-events-tests/TaskRunnerTests.swift
- tests/offline-events-tests/TaskSchedulerTests.swift
- tests/swift-sdk-swift-tests/in-app-tests/InAppPriorityTests.swift
- tests/swift-sdk-swift-tests/in-app-tests/InAppTests.swift
- tests/swift-sdk-swift-tests/inbox-tests/InboxTests.swift
* [MOB-2601](https://iterable.atlassian.net/browse/MOB-2601)
> 
1. Fixed MockNotificationCenter to not hold strong references. 
2. InAppManager, avoid using strong references when using callbacks. 
3. Uncommented failing test in InAppPriorityTests.
> [MOB-2601] - Memory leak

- swift-sdk/Internal/IterableCoreDataPersistence.swift
- tests/endpoint-tests/OfflineModeE2ETests.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/offline-events-tests/TaskProcessorTests.swift
- tests/offline-events-tests/TaskRunnerTests.swift
- tests/offline-events-tests/TaskSchedulerTests.swift
- tests/offline-events-tests/TasksCRUDTests.swift
* [MOB-2614](https://iterable.atlassian.net/browse/MOB-2614)
> If our customer app is using Swift package manager and they are initializing and using our SDK in a separate framework, core data would not be initialized because data model file would not be located. Fixed this by searching for resources from main bundle instead of framework bundle.
> [MOB-2614] - Offline mode not initialized when including IterableSDK from a framework bundle.

- .github/pull_request_template.md
- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/CoreDataUtil.swift
- swift-sdk/Internal/InAppCalculations.swift
- swift-sdk/Internal/InAppContentParser.swift
- swift-sdk/Internal/InAppDisplayer.swift
- swift-sdk/Internal/InAppHelper.swift
- swift-sdk/Internal/InAppManager+Functions.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/InboxViewControllerViewModel.swift
- swift-sdk/Internal/IterableCoreDataPersistence.swift
- swift-sdk/Internal/IterableHtmlMessageViewController.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/IterableAPI.swift
- swift-sdk/IterableInboxNavigationViewController.swift
- swift-sdk/IterableInboxViewController.swift
- swift-sdk/IterableMessaging.swift
- tests/swift-sdk-swift-tests/InAppMessageProcessorTests.swift
- tests/swift-sdk-swift-tests/InAppParsingTests.swift
- tests/swift-sdk-swift-tests/InAppPersistenceTests.swift
- tests/swift-sdk-swift-tests/InAppTests.swift
- ui-tests-app/ViewController.swift
* [MOB-2769](https://iterable.atlassian.net/browse/MOB-2769)
* version 6.2.21 with read state and no messages view
> [MOB-2769] version 6.2.21

- swift-sdk/IterableInboxViewController.swift
* [MOB-2778](https://iterable.atlassian.net/browse/MOB-2778)
> No message labels were being cut off when they were too long. Limited the width.
> [MOB-2778] - Limit width of "no-messages" labels.

- swift-sdk/Internal/InternalIterableAPI.swift
* [MOB-2646](https://iterable.atlassian.net/browse/MOB-2646)
> Mobile deeplinking request to server was returning a failure from server. Turns out that we were not sending "application/json" header to server.
> [MOB-2646]- Deferred deeplinking returning error

- Iterable-iOS-SDK.podspec
* [MOB-3251](https://iterable.atlassian.net/browse/MOB-3251)
* add `header_dir` to the SDK Podspec so that `use_frameworks!` doesn't need to be in the Podfile anymore
> [MOB-3251] add header_dir to podspec

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/AppExtensionHelper.swift
- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/IterableActionRunner.swift
- swift-sdk/Internal/IterableAppIntegrationInternal.swift
- swift-sdk/Internal/IterableUtil.swift
- swift-sdk/IterableAPI.swift
- swift-sdk/IterableInboxViewController.swift
- tests/common/CommonExtensions.swift
- tests/endpoint-tests/E2EDependencyContainer.swift
* [MOB-3277](https://iterable.atlassian.net/browse/MOB-3277)
> UIApplication.shared and url opening is not app extension safe. They should not be called from app extensions.
This PR is related to Github issue https://github.com/Iterable/swift-sdk/issues/488.
> [MOB-3277] - Move all app extension unsafe code to AppExtensionHelper class

- swift-sdk/swiftui/InboxViewRepresentable.swift
- swift-sdk/swiftui/IterableInboxView.swift
* [MOB-3835](https://iterable.atlassian.net/browse/MOB-3835)
> Archiving is failing because SwiftUI does not work for Armv7. Exclude it.
> [MOB-3835] - Fix archive issue SwiftUI doesn't build for  armv7

- swift-sdk/Internal/InboxSessionManager.swift
* [MOB-3973](https://iterable.atlassian.net/browse/MOB-3973)
* adds back an initializer of `InboxSessionManager` that the RN SDK was relying on
> [MOB-3973] add initializer for inboxsessionmanager

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/InternalIterableAppIntegration.swift
- swift-sdk/IterableAppIntegration.swift
- tests/unit-tests/InAppTests.swift
- tests/unit-tests/IterableNotificationResponseTests.swift
* [MOB-4000](https://iterable.atlassian.net/browse/MOB-XXXX)
> Refactor => Rename
The last part (right most part) of naming should be what the class is. And progressively each part from right to left should give more specific detail. Internal is a detail and not what the class is.
> [MOB-4000] - Rename IterableAppIntegrationInternal => InternalIterableAppIntegration

- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/OfflineRequestProcessor.swift
- swift-sdk/Internal/RequestCreator.swift
- tests/offline-events-tests/TaskProcessorTests.swift
- tests/offline-events-tests/TaskRunnerTests.swift
- tests/offline-events-tests/TaskSchedulerTests.swift
- tests/unit-tests/RequestCreatorTests.swift
* [MOB-4287](https://iterable.atlassian.net/browse/MOB-4287)
> Removes the api-key argument from the url and only passes it in the header of the request to ensure security.
> [MOB-4287] Removes the extra api-key argument from the request creator.

- swift-sdk/IterableAPI.swift
* [MOB-4689](https://iterable.atlassian.net/browse/MOB-4689)
* add set email and userId functions into public space
> [MOB-4689] add set functions into public space

- swift-sdk/Internal/DependencyContainer.swift
- swift-sdk/Internal/InAppManager.swift
* [MOB-5337](https://iterable.atlassian.net/browse/MOB-5337)
1. Replace instances of retryInterval to moveToForegroundSyncInterval.
2. Map inAppDisplayInterval to moveToForegroundSyncInterval rather than converting to retryInterval
Context:
The configurable inAppDisplayInteval maps to variable - retryInterval which is used to check if its ready to show inapp after first inapp was displayed. However, the same property is not used when app switches from background to foreground. During this time, a variable - moveToForegroundSyncInterval is used which is redundant and is never changed.
> [MOB-5337] - InAppDisplayInterval resolution

- swift-sdk/Internal/AuthManager.swift
Before creating a new expirationRefreshTimer clear any previous timers
If you call setUserId multiple times from the react-native-sdk timer it will register a timer for refreshing them and call the authHandler multiple times. This prevents any possible duplicate timer situations.
> [AuthManager] clear token refresh timer

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/IterableAPI.swift
* [MOB-5940](https://iterable.atlassian.net/browse/MOB-5940)
[MOB-5940]: https://iterable.atlassian.net/browse/MOB-5940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5940] version 6.4.12

- swift-sdk.xcodeproj/project.pbxproj
- tests/unit-tests/BlankApiClient.swift
- tests/unit-tests/InAppHelperTests.swift
* [MOB-5970](https://iterable.atlassian.net/browse/MOB-5970)
* creates a "blank" API client for unit test overriding (where we want to test only a subset of API client functions)
[MOB-5970]: https://iterable.atlassian.net/browse/MOB-5970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-5970] create and use blank API client

- swift-sdk/Internal/InAppPersistence.swift
* [MOB-6106](https://iterable.atlassian.net/browse/MOB-6106)
> Use Application Support Directory instead of Default document directory to store files required by SDK so that the files is not visible to user in Files App.
File is stored by the SDK in document directory provided by FileManager [as shown here](https://github.com/Iterable/swift-sdk/blob/fd55d0ae5e182430f79f98430e85bb44d29bc7f7/swift-sdk/Internal/InAppPersistence.swift#L414). 
Looks like (References [#](https://www.hackingwithswift.com/books/ios-swiftui/writing-data-to-the-documents-directory), [#](https://stackoverflow.com/a/57333725) and [#](https://developer.apple.com/documentation/foundation/filemanager/searchpathdirectory/applicationsupportdirectory)) :  
Some apps can have their default Filemanager access the directory …
> [MOB - 6106] - Use Application Directory

- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/EmptyEmbeddedMessagingManager.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/IterableEmbeddedMessagingManagerProtocol.swift
* [MOB-6038](https://iterable.atlassian.net/browse/MOB-6038)
This PR makes the Iterable SDK use Iterable events for click and delivery events on embedded messages instead of the track api
[MOB-6038]: https://iterable.atlassian.net/browse/MOB-6038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6038] Use Iterable events for click and delivery instead of track api

- swift-sdk/Constants.swift
* [MOB-6317](https://iterable.atlassian.net/browse/MOB-6317)
> Fixes the enum to make it publicly available to RN SDK 
[MOB-6317]: https://iterable.atlassian.net/browse/MOB-6317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6317] make data region enum accessible

- swift-sdk/Internal/EmbeddedMessagingManager.swift
- swift-sdk/Internal/EmbeddedMessagingProcessor.swift
- swift-sdk/Internal/EmbeddedMessagingSerialization.swift
- swift-sdk/Internal/EmbeddedSessionManager.swift
- swift-sdk/Internal/RequestCreator.swift
- swift-sdk/IterableEmbeddedMessage.swift
- tests/embedded-messaging-tests/EmbeddedMessagingProcessorTests.swift
This PR fixes the custom payload decoding in embedded messages. Should work on most standard JSON structures. Tested with the following payload:
```
{
"test": null,
"testObj": [
{
"testObjKey1": 1,
"testObjKey2": "two"
},
{
"testObj2Key1": {
"Obj2NestedKey1": 1,
"obj2NestedKey2": "two"
},
"testObj2key2": "2"
}
],
"messageImportance": "low"
}
```
> Fix custom payload decoding

- swift-sdk/Internal/RequestCreator.swift
* [MOB-6356](https://iterable.atlassian.net/browse/MOB-6356)
This PR enables UID in embedded message requests. If the user is signed in via email, it will use email. If the user is signed in via uid, it will use uid when making requests to the API.
[MOB-6356]: https://iterable.atlassian.net/browse/MOB-6356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6356] Use email or uid when making requests to api

- .github/workflows/e2e.yml
- tests/endpoint-tests/CI.swift.template
- tests/endpoint-tests/EndpointTests.swift
- tests/endpoint-tests/Environment.swift
- tests/endpoint-tests/IterableAPISupport.swift
- tests/endpoint-tests/scripts/env_vars.sh.sample
- tests/endpoint-tests/scripts/run_test.sh
This PR fixes integration test failures related to:
1. No proper server key for sending in app messages (e.g. /inApp/target) via IterableAPISupport
2. The mobile SDK test project caching is broken somehow so that calling getMessages yields a set of messages each with the same data, including messageIds, none of which correspond to the actual messageIds for a user's non-consumed messages. This means we cannot consume those messages via our integration test, causing the tests to fail.
> fix integration tests

- swift-sdk/Internal/EmbeddedSessionManager.swift
Fixes a bug where embedded impressions count could increase when reforegrounding the app. startImpression(messageId:) will simply return if the message (associated by the messageId) is already being tracked.
> Fix Start Embedded Impression duplicates

- swift-sdk.xcodeproj/xcshareddata/xcschemes/swift-sdk.xcscheme
- swift-sdk/Internal/DependencyContainerProtocol.swift
- swift-sdk/Internal/RequestHandler.swift
* [MOB-6583](https://iterable.atlassian.net/browse/MOB-6583)
> 1. Turned the default value to false instead of true. Only once the response comes back as true, the value will be set to true. Subsequent launches will respect whats stored after that. There will not be a toggling happening every now and then. Once the response from server is received as true, its stored in the sdk.
> 2. Create RequestHandler initializes both online and offline request Handler irrespective of the feature enabled or disabled. Added lazy var for offlineprocessor and initializing offline componenents only when offlineMode is true.
This change will make sure that components like TaskSchedular and HealthMonitor will not be even initialized unless offlineMode is true. However, this change does not engage …
> [MOB - 6583] - No Offline Components when Online-Only

- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/EmbeddedMessagingSerialization.swift
- swift-sdk/Internal/EmptyEmbeddedManager.swift
- swift-sdk/Internal/IterableEmbeddedManager.swift
- swift-sdk/IterableEmbeddedManagerProtocol.swift
- swift-sdk/IterableEmbeddedMessage.swift
- tests/embedded-messaging-tests/EmbeddedManagerTests.swift
- tests/unit-tests/BlankApiClient.swift
* [MOB-6648](https://iterable.atlassian.net/browse/MOB-6648)
This pull request updates the syncMessages function to pull messages from the placement object in the payload.
[MOB-6648]: https://iterable.atlassian.net/browse/MOB-6648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-6648] update get messages to pull messages from placement

- tests/common/MockAuthManager.swift
- tests/unit-tests/IterableAPIResponseTests.swift
* [MOB-7153](https://iterable.atlassian.net/browse/MOB-7153)
> Unit test for InvalidJwtPayload retry
[MOB-7153]: https://iterable.atlassian.net/browse/MOB-7153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Unit tests for InvalidJwtPayload retry

- swift-sdk/Internal/NetworkHelper.swift
- tests/unit-tests/IterableAPIResponseTests.swift
* [MOB-7021](https://iterable.atlassian.net/browse/MOB-7021)
> This pull request implements retry mechanism for failed network requests along with associated tests. Credit: omni-cg.
[MOB-7021]: https://iterable.atlassian.net/browse/MOB-7021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7021] Implement retry mechanism to the iOS SDK for failed network requests

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/RequestProcessorUtil.swift
- tests/common/MockAuthManager.swift
- tests/unit-tests/AuthTests.swift
- tests/unit-tests/IterableAPIResponseTests.swift
* [MOB-7153](https://iterable.atlassian.net/browse/MOB-7153)
> This pull request updates the `sendRequest` function in `RequestProcessorUtil` to request a new auth token regardless of if the prior authentication attempt failed. Credit: Omni-CG.
[MOB-7153]: https://iterable.atlassian.net/browse/MOB-7153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7153] Implement JWT Retry Logic for iOS SDK

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-7313](https://iterable.atlassian.net/browse/MOB-7313)
> This pull request prepares for the 6.5.0-beta1 release.
[MOB-7313]: https://iterable.atlassian.net/browse/MOB-7313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7313] prepare 6.5.0-beta1 release

- swift-sdk/Internal/IterableTaskRunner.swift
Fixed TaskRunner pause
* [MOB-7031](https://iterable.atlassian.net/browse/MOB-7031)
Fixes TaskRunner pause state; running flag never being set to false
[MOB-7031]: https://iterable.atlassian.net/browse/MOB-7031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed MOB-7031

- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
* [QAE-1038](https://iterable.atlassian.net/browse/QAE-1038)
During testing of automated release in Github Actions, master branch was unintentionally updated with a testing version number for `.podspec` files. This PR will reset to correct version.
To prevent this in the future, Github Actions should not be run on master but a branch.
[QAE-1038]: https://iterable.atlassian.net/browse/QAE-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QAE-1038] set pods to correct version - 6.4.16

- swift-sdk/Internal/IterableEmbeddedManager.swift
- swift-sdk/uicomponents/IterableEmbeddedView.swift
* [MOB-7458](https://iterable.atlassian.net/browse/MOB-7458)
Config object
Enum for type
Removal of ViewDelegate and its methods
[MOB-7458]: https://iterable.atlassian.net/browse/MOB-7458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7458] - Aligning iOS with Android

- CHANGELOG.md
- swift-sdk/IterableAPI.swift
* [MOB-7488](https://iterable.atlassian.net/browse/MOB-7488)
[6.4.17]
Changed
IterableTaskRunner’s stop function now to set running variable as false
[MOB-7488]: https://iterable.atlassian.net/browse/MOB-7488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7488] changelog and bump IterableAPI to v6.4.17

- swift-sdk/uicomponents/IterableEmbeddedView.swift
* [MOB-7565](https://iterable.atlassian.net/browse/MOB-7565)
> Updates the way the nib for IterableEmbeddedView is instatiated per the slack thread [here](https://iterable.slack.com/archives/C03V4A5F3LP/p1704240697853559).
[MOB-7565]: https://iterable.atlassian.net/browse/MOB-7565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7565] use bundle.module when loading IterableEmbeddedView

- swift-sdk/Resources/IterableEmbeddedView.xib
- swift-sdk/uicomponents/IterableEmbeddedView.swift
* [MOB-7654](https://iterable.atlassian.net/browse/MOB-7654)
> This pull request aligns the available configurations with the Android SDK.
* provides a default font for title and body
* removes IBinspectables - I want to investigate the use of this on a separate ticket
* removes redundant `setDefaultValue` function
* renames property names
* sets default of buttons to have rounded sides
Associated bugs:
* [MOB-7602](https://iterable.atlassian.net/browse/MOB-7602)
* [MOB-7601](https://iterable.atlassian.net/browse/MOB-7601)
[MOB-7654]: https://iterable.atlassian.net/browse/MOB-7654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-7602]: https://iterable.atlassian.net/browse/MOB-7602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
> [MOB-7654] config alignment

- swift-sdk/Internal/DependencyContainerProtocol.swift
- swift-sdk/Internal/IterableEmbeddedManager.swift
- swift-sdk/IterableConfig.swift
- tests/unit-tests/EmbeddedManagerTests.swift
* [MOB-7733](https://iterable.atlassian.net/browse/MOB-7733)
Disables fetching embedded messages by default and adds a config to turn it on.
[MOB-7733]: https://iterable.atlassian.net/browse/MOB-7733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7733] doesn't fetch embedded messages by default, adds a config option

- swift-sdk/Resources/IterableEmbeddedView.xib
- swift-sdk/uicomponents/IterableEmbeddedView.swift
* [MOB-7748](https://iterable.atlassian.net/browse/MOB-7748)
[MOB-7748]: https://iterable.atlassian.net/browse/MOB-7748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7748] iOS constraints fix for banner img view

- .github/workflows/ios-sdk-release.yml
- fastlane/Fastfile
* [MOB-7595](https://iterable.atlassian.net/browse/MOB-7595)
Updating the iOS SDK automation release by separating the bump version step of podspecs from the rest of the process. This ensures a cleaner solution as bump version requires a code merge, whereas the rest of the release steps do not.
Please see the updated [slab doc](https://iterable.slab.com/posts/automated-i-os-sdk-release-es6hjhxs)
[MOB-7595]: https://iterable.atlassian.net/browse/MOB-7595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-7595] iOS SDK Release automation refactor

- swift-sdk/Constants.swift
- swift-sdk/Internal/AnonymousUserManager+Functions.swift
- swift-sdk/Internal/AnonymousUserManager.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/Models.swift
- swift-sdk/Internal/RequestCreator.swift
> merge all other AUT branch code

- swift-sdk/Internal/WebViewProtocol.swift
- tests/common/MockWebView.swift
Removing the protocol method as SDK uses the default WKWebview method
* [MOB-9021](https://iterable.atlassian.net/browse/MOB-9021)
> Remove protocol method
[MOB-9021]: https://iterable.atlassian.net/browse/MOB-9021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9021] - Remove protocol method

- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/IterableAPI.swift
- tests/unit-tests/UserMergeScenariosTests.swift
* [MOB-9109](https://iterable.atlassian.net/browse/MOB-9109)
> This pull request adds a check for the anonymous user id in local storage. Merging should only occur when there is an anonymous user logged in.
[MOB-9109]: https://iterable.atlassian.net/browse/MOB-9109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9109] adds anonymous user id stored check

- swift-sdk/Internal/NetworkHelper.swift
- swift-sdk/Internal/RequestSender.swift
- tests/unit-tests/IterableAPIResponseTests.swift
* [MOB-9192](https://iterable.atlassian.net/browse/MOB-9192)
> Removing the generic error mapping at Request Handling layer. This is what gets read further and appropriate AuthFailure reasons will be passed to the app.
[MOB-9192]: https://iterable.atlassian.net/browse/MOB-9192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Mob 9192 JWT error Mapping

- swift-sdk/AuthFailureReason.swift
- swift-sdk/Internal/RequestProcessorUtil.swift
Removing additional reason in iOS SDK
* [MOB-9320](https://iterable.atlassian.net/browse/MOB-9320)
> AuthFailure parity with Android
[MOB-9320]: https://iterable.atlassian.net/browse/MOB-9320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9320] - AuthFailure parity with Android

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Constants.swift
- tests/unit-tests/ComparatorTypeDoesNotEqualMatchTest.swift
- tests/unit-tests/DataTypeComparatorSearchQueryCriteria.swift
* [MOB-9138](https://iterable.atlassian.net/browse/MOB-9138)
> DoesNotEqual does not seem to work for string, double, long, boolean
[MOB-9138]: https://iterable.atlassian.net/browse/MOB-9138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-9138: Resolves DoesNotEqual criteria match issue

- swift-sdk/Internal/APNSTypeChecker.swift
* [MOB-9247](https://iterable.atlassian.net/browse/MOB-9247)
SDK checks if the target is a simulator
if so > APNS SANDBOX
if not > read the file 'embedded.provision'
Check if certain value exist to mark it as APNSSANDBOX If not, default it to PRODUCTION APNS.
Using Xcode 16 beta with iOS 18 beta, we discovered that file reading was failing with normal ASCII encoding.
File was able to type to data easily.
Once the data was available, now we try to read the file with all encoding available to us now. If none of them works, we print ITBLError. The first one to decode the file proceeds with scan operation - finding the right tags and keywords.
- Tested with Xcode GA and Beta and iOS 17 and iOS 18 devices
[MOB-9247]: https://iterable.atlassian.net/browse/MOB-9247?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
> [MOB-9247] - Bug fix for no push on APNS SANDBOX

- swift-sdk/Internal/AnonymousUserManager.swift
- swift-sdk/Internal/ApiClient.swift
- swift-sdk/Internal/ApiClientProtocol.swift
- swift-sdk/Internal/RequestCreator.swift
- tests/unit-tests/BlankApiClient.swift
* [MOB-9449](https://iterable.atlassian.net/browse/MOB-9449)
> Update user should not be a separate call
##Test Steps
[MOB-9449]: https://iterable.atlassian.net/browse/MOB-9449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-9449: update user should not be a separate call

- tests/unit-tests/DeepLinkTests.swift
* [MOB-7855](https://iterable.atlassian.net/browse/MOB-7855)
This is a pull request to fix https://github.com/Iterable/swift-sdk/issues/592
Verified it fixes the issue still present in 6.5.4
[MOB-7855]: https://iterable.atlassian.net/browse/MOB-7855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bug fix/mob 7855 universal link behavior

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/AuthManager.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- tests/unit-tests/ValidateStoredEventCheckUnknownToKnownUserTest.swift
* [MOB-9517](https://iterable.atlassian.net/browse/MOB-9517)
[MOB-9517]: https://iterable.atlassian.net/browse/MOB-9517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> - events are not getting replayed (unknown user to known user)

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/AnonymousUserManager+Functions.swift
- tests/unit-tests/AnonymousUserComplexCriteriaMatchTests.swift
- tests/unit-tests/AnonymousUserCriteriaIsSetTests.swift
- tests/unit-tests/AnonymousUserCriteriaMatchTests.swift
- tests/unit-tests/ComparatorDataTypeWithArrayInput.swift
- tests/unit-tests/CustomEventUserUpdateTestCaseTests.swift
- tests/unit-tests/ValidateCustomEventUserUpdateAPITest.swift
* [MOB-9306](https://iterable.atlassian.net/browse/MOB-9306)
> Add test to validate object created by custom event api calls
[MOB-9306]: https://iterable.atlassian.net/browse/MOB-9306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> - Add test to validate object created by custom event API calls

- tests/unit-tests/CombinationComplexCriteria.swift
* [MOB-9727](https://iterable.atlassian.net/browse/MOB-9727)
> This pull request adds an additional test case for complex criteria #3 test so that both possible passing events are covered. I will add this case to Android too for parity.
[MOB-9727]: https://iterable.atlassian.net/browse/MOB-9727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9727] additional complex criteria test

- tests/unit-tests/UserMergeScenariosTests.swift
- tests/unit-tests/ValidateStoredEventCheckUnknownToKnownUserTest.swift
* [MOB-9646](https://iterable.atlassian.net/browse/MOB-9646)
> This pull request aligns the unit test naming with the Android SDK and also adds tests to cover all the identity resolution combinations.
[MOB-9646]: https://iterable.atlassian.net/browse/MOB-9646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9646] update UserMergeScenarioTests to include all identity resolution parameter combinations

- swift-sdk/Internal/AnonymousUserManager.swift
- swift-sdk/Internal/AnonymousUserManagerProtocol.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- tests/unit-tests/UserMergeScenariosTests.swift
- tests/unit-tests/ValidateStoredEventCheckUnknownToKnownUserTest.swift
* [MOB-9974](https://iterable.atlassian.net/browse/MOB-9974)
> This pull request updates attemptAndProcessMerge to call syncEvents directly. Also, modifies flow to set userId/email before attempting event replay.
[MOB-9974]: https://iterable.atlassian.net/browse/MOB-9974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9974] fix event replay from visitor to known user

- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/IterableAPI.swift
- swift-sdk/IterableConfig.swift
- tests/unit-tests/DataTypeComparatorSearchQueryCriteria.swift
- tests/unit-tests/UserMergeScenariosTests.swift
- tests/unit-tests/ValidateCustomEventUserUpdateAPITest.swift
- tests/unit-tests/ValidateStoredEventCheckUnknownToKnownUserTest.swift
- tests/unit-tests/ValidateTokenForDestinationUserTest.swift
* [MOB-10093](https://iterable.atlassian.net/browse/MOB-10093)
> This pull request updates the config to enableAnonActivation.
[MOB-10093]: https://iterable.atlassian.net/browse/MOB-10093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10093] final cleanup

- swift-sdk/Internal/AnonymousUserManager.swift
- swift-sdk/Internal/AnonymousUserManagerProtocol.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- tests/unit-tests/UserMergeScenariosTests.swift
* [MOB-10136](https://iterable.atlassian.net/browse/MOB-10136)
> This pull request updates attemptAndProcessMerge to clear the local storage when replay is false.
[MOB-10136]: https://iterable.atlassian.net/browse/MOB-10136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10136] clears local storage when replay is false

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/InAppManager+Functions.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/ThreadSafeOrderedDictionary.swift
- tests/unit-tests/InAppMessageProcessorTests.swift
- tests/unit-tests/ThreadSafeOrderedDictionaryTests.swift
`InAppManager` can crash as stated in [this issue](https://github.com/Iterable/iterable-swift-sdk/issues/582) due to `OrderedDictionary` not being thread safe. This change introduces `ThreadSafeOrderedDictionary` which is a wrapper around it to ensure thread safety. To minimize changes I have introduced it only where needed. In the future it would be a good idea to look at making `OrderedDictionary` safe by itself.
Tests for concurrency safety have also been added.
> Created ThreadSafeOrderedDictionary Wrapper

- swift-sdk/Internal/DependencyContainerProtocol.swift
- swift-sdk/Internal/IterableCoreDataPersistence.swift
- tests/common/CommonExtensions.swift
- tests/endpoint-tests/OfflineModeE2ETests.swift
- tests/offline-events-tests/HealthMonitorTests.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/offline-events-tests/TaskProcessorTests.swift
- tests/offline-events-tests/TaskRunnerTests.swift
- tests/offline-events-tests/TaskSchedulerTests.swift
- tests/offline-events-tests/TasksCRUDTests.swift
This PR prevents a crash which occurs when Core Data's persistent store fails to load. Loading the persistent store can fail for several reasons: the database could be corrupted, the disk might be full, or from a bad migration. This also might occur when the app wakes up in the background and the persistent store didn't load in time.
When using `NSPersistentContainer` it's important to handle any errors from `loadPersistentStores(_:)` since they're recoverable. If you ignore this error, then Core Data throws an Objective-C exception which cannot be handled in Swift when you try to save.
Previous PR #816 
The crash originates from `IterableTaskScheduler.deleteAllTasks()` which calls try `persistenceContext.save()` and throws:
```
NSInternalInconsistencyException - This …
```
> Stopping Core Data Crashes When Disk is Full

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Internal/InAppManager+Functions.swift
- swift-sdk/Internal/InAppManager.swift
- swift-sdk/Internal/ThreadSafeOrderedDictionary.swift
- tests/unit-tests/InAppMessageProcessorTests.swift
- tests/unit-tests/ThreadSafeOrderedDictionaryTests.swift
* [MOB-10312](https://iterable.atlassian.net/browse/MOB-10312)
> > This pull request merges the introduction of a thread safe dictionary suggested [here](https://github.com/Iterable/iterable-swift-sdk/pull/860) into the beta version branch.
[MOB-10312]: https://iterable.atlassian.net/browse/MOB-10312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10312] thread safe ordered dictionary wrapper

- swift-sdk/Constants.swift
- swift-sdk/Internal/InternalIterableAPI.swift
* [MOB-10104](https://iterable.atlassian.net/browse/MOB-10104)
When a Push notification with the Wakey feature tuned on — `"content-available": 1` — the SDK was tracking a pushOpen event incorrectly.
Now we actively check if it's a wakey push notification and prevent that tracking — unless the user actually taps on the notification and opens the app.
[MOB-10104]: https://iterable.atlassian.net/browse/MOB-10104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10104] Fix wakey notification tracking event on did finish launch with options 

- swift-sdk/Internal/InternalIterableAppIntegration.swift
```swift
let config = IterableConfig()
config.autoPushRegistration = false
IterableAPI.initialize(apiKey: apiKey, launchOptions: launchOptions, config: config)
```
If you take into consideration that the user has `autoPushRegistration` set to false, the SDK will return `notificationsEnabled` set to true due to this bug. If `autoPushRegistration` is set to false, the user often has `UNAuthorizationStatus` set to `.notDetermined`.  
This change fixes this issue so that by default SDK should return the proper value
> Take into consideration not determined status into checking notifications access status

- CHANGELOG.md
- Iterable-iOS-AppExtensions.podspec
- Iterable-iOS-SDK.podspec
- swift-sdk/IterableAPI.swift
* [MOB-10468](https://iterable.atlassian.net/browse/MOB-10468)
> This pull request prepares for the version 6.5.8 release.
[MOB-10468]: https://iterable.atlassian.net/browse/MOB-10468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10468] prepare version 6.5.8 release

- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk/Core/Constants.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/IterableUserDefaults.swift
- swift-sdk/Internal/Utilities/LocalStorage.swift
- swift-sdk/Internal/Utilities/LocalStorageProtocol.swift
- tests/common/MockLocalStorage.swift
- tests/unit-tests/AutoRegistrationTests.swift
- tests/unit-tests/Mocks.swift
- tests/unit-tests/NotificationObserverTests.swift
* [MOB-9445](https://iterable.atlassian.net/browse/MOB-9445)
> This PR introduces enhanced notifications permissions tracking. The changes were cherry picked from the PR [here](https://github.com/Iterable/iterable-swift-sdk/pull/879) to merge into master for release.
[MOB-9446]: https://iterable.atlassian.net/browse/MOB-9446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-9445]: https://iterable.atlassian.net/browse/MOB-9445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-9446] Enhance push notification state tracking in SDKs

- CHANGELOG.md
- swift-sdk.xcodeproj/project.pbxproj
- swift-sdk.xcodeproj/xcshareddata/xcschemes/swift-sdk.xcscheme
- swift-sdk/Core/Constants.swift
- swift-sdk/Internal/DataFieldsHelper.swift
- swift-sdk/Internal/InternalIterableAPI.swift
- swift-sdk/Internal/IterableAPIMobileFrameworkDetector.swift
- swift-sdk/Internal/api-client/Request/RequestCreator.swift
- swift-sdk/Internal/api-client/Request/RequestProcessorProtocol.swift
- swift-sdk/SDK/IterableConfig.swift
- tests/offline-events-tests/RequestHandlerTests.swift
- tests/unit-tests/IterableAPITests.swift
- tests/unit-tests/RequestCreatorTests.swift
- tests/unit-tests/TestUtils.swift
* [MOB-10591](https://iterable.atlassian.net/browse/MOB-10591)
Add mobile framework info to iOS according to spec
[MOB-10591]: https://iterable.atlassian.net/browse/MOB-10591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Please read the full spec at https://iterable.slab.com/posts/mobile-datadog-dashboard-flutter-rn-support-fd6p2n7e?shr=6m4blt3qaTsWYn38av0w-Mkg
> [MOB-10951] Add mobile framework info to register token request

- swift-sdk/Internal/InternalIterableAPI.swift
* [MOB-10770](https://iterable.atlassian.net/browse/MOB-10770)
On the Project Anonymous User we are already using this checks. This task aims at bringing those checks to the main branch of the SDK work.
[MOB-10770]: https://iterable.atlassian.net/browse/MOB-10770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-10770 Update iOS SDK initialization checks

- swift-sdk/Core/Constants.swift
- swift-sdk/Internal/AnonymousUserManager.swift
* [MOB-10781](https://iterable.atlassian.net/browse/MOB-10781)
> This pull request updates the cooldown period constant to be in milliseconds. The `lastCriteriaFetch` is logged in milliseconds so the cooldown period needs to be too.
[MOB-10781]: https://iterable.atlassian.net/browse/MOB-10781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-10781] updates cooldown period constant

- swift-sdk/ui-components/uikit/IterableEmbeddedView.swift
* [MOB-9982](https://iterable.atlassian.net/browse/MOB-9982)
Instead of force unwrapping a potential nil value stored on the imgView and cardImageView components, we now use optionals to prevent a crash.
[MOB-9982]: https://iterable.atlassian.net/browse/MOB-9982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-9982 Embedded messaging crash when image fails to load

- swift-sdk/Internal/AnonymousUserManager.swift
- tests/unit-tests/IterableApiCriteriaFetchTests.swift
- tests/unit-tests/UserMergeScenariosTests.swift
* [MOB-10807](https://iterable.atlassian.net/browse/MOB-10807)
> Multiple unique anonymous users are created.
Video attached for end result on tickets like how resolved the issue.
[MOB-10807]: https://iterable.atlassian.net/browse/MOB-10807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix AUT issue where multiple users are created and merge

- sample-apps/swift-sample-app/swift-sample-app.xcodeproj/project.pbxproj
- sample-apps/swift-sample-app/swift-sample-app.xcodeproj/xcshareddata/xcschemes/internal-swift-sample-app.xcscheme
Added configuration flexibility to the Swift Sample App to better support both external developers and Iterable internal usage.
1. Modified Debug/Release configurations:
- Set empty development team (`DEVELOPMENT_TEAM = ""`)
- Set wildcard bundle identifier (`PRODUCT_BUNDLE_IDENTIFIER = "*"`)
- This allows developers to easily set up their own team and bundle ID
2. Added new "Internal" configuration for both targets:
- Main app:
- Set Iterable's team ID (`DEVELOPMENT_TEAM = "BP98Z28R86"`)
- Set specific bundle ID (`com.iterable.swift-sample-app`)
- Notification extension:
- Set Iterable's team ID (`DEVELOPMENT_TEAM = "BP98Z28R86"`)
- Set specific bundle ID (`com.iterable.swift-sample-app.notification-extension`)
This change addresses two key needs:
1. External developers can now open and …
> ✨ Improve sample app build config

- swift-sdk/Internal/IterableEmbeddedManager.swift
* [MOB-11252](https://iterable.atlassian.net/browse/MOB-11252)
Using DispatchQueue when setting and reading the messages.
[MOB-11252]: https://iterable.atlassian.net/browse/MOB-11252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-11252] - Sequential accessing EM

- swift-sdk/Internal/ActionRunner.swift
- tests/hosting-apps/ui-tests-app/ViewController.swift
- tests/notification-extension-tests/NotificationExtensionTests.swift
- tests/ui-tests/UITests.swift
- tests/unit-tests/DeepLinkTests.swift
- tests/unit-tests/InAppParsingTests.swift
- tests/unit-tests/IterableAPITests.swift
* [MOB-8537](https://iterable.atlassian.net/browse/MOB-8537)
> This pull request updates the action runner to check if protocol is allowed before checking if url can be handled by the url handler or custom action handler.
[MOB-8537]: https://iterable.atlassian.net/browse/MOB-8537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-8537] updates action runner logic to check allowed protocols

- swift-sdk/Internal/InternalIterableAPI.swift
- tests/unit-tests/ConsentTrackingTests.swift
* [MOB-11789](https://iterable.atlassian.net/browse/MOB-11789)
> > This pull request moves the consent tracking to be called after successful registering of device.
[MOB-11789]: https://iterable.atlassian.net/browse/MOB-11789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MOB-11789] consent logging triggered by successful register call

- .github/workflows/build-and-test.yml
- tests/endpoint-tests/scripts/run_test.sh
- **GitHub Workflow**: 
- Updated `.github/workflows/build-and-test.yml` to dynamically detect the latest stable iOS 18.x version instead of hardcoding `18.2`
- **Endpoint Tests**: 
- Updated `tests/endpoint-tests/scripts/run_test.sh` to use the same dynamic detection instead of hardcoding `18.1`
> 🧪 Updates the script to use the latest stable version of iOS available

- swift-sdk/Internal/CoreDataUtil.swift
- swift-sdk/Internal/IterableCoreDataPersistence.swift
* [MOB-12033](https://iterable.atlassian.net/browse/MOB-12033)
Renames a conflicting method name with the native CoreData one.
Versions older than iOS 15 will use the custom method, newer versions will use the native one.
Thank you @fnazarios and @rajusa420 for raising this issue!
[MOB-12033]: https://iterable.atlassian.net/browse/MOB-12033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-12033 Renamed CoreData method for iOS 26 compatibility
